/* =========================================================
   PLANNING DU SÉJOUR — Fukuoka, oct. à déc. 2026
   Rien n'est figé : dans l'app tu peux déplacer, retirer,
   ajouter une sortie ou la marquer comme faite. Ces changements
   restent sur ton téléphone ; ce fichier est le plan de base.

   SORTIES : une entrée par sortie
     t     titre court          d     ton texte
     info  « À savoir »
     full  journée entière (pas de salle ce jour-là)
     morning  occupe la matinée (pas de salle)
     evening  se passe le soir
     city  autre ville          night ville où tu dors
     out   repas pris dehors : breakfast / lunch / dinner
     pass  jour de pass JR
     p     lieux : [nom, recherche Apple Plans]
   ========================================================= */

window.TRIP = {
  start: "2026-10-03",
  end: "2026-12-20",
  tokyo: { from: "2026-10-27", to: "2026-11-04" },
  months: {
    9: { name: "Octobre", theme: "La mer, les fleurs et Nagasaki", intro: "Octobre profite de la douceur : îles, champs de fleurs et la côte d'Itoshima." },
    10: { name: "Novembre", theme: "Les feuillages et Hiroshima", intro: "Les érables sont au plus beau de la mi à la fin novembre. Les jardins de la ville sont placés en semaine, les sites éloignés le week-end." },
    11: { name: "Décembre", theme: "Onsen, illuminations et adieux", intro: "Décembre est plus calme en semaine. Les week-ends vont aux onsen de Beppu et à Kitakyushu." },
  },
};

/* ---------- Sorties ----------
   d    = ton texte (colonne « Après-midi / journée »)
   info = ton texte (colonne « À savoir »)
   p    = lieux : [nom, recherche Apple Plans, { a: adresse, w: site }]
   Les autres champs servent à l'app (journée entière, ville, nuit…). */
const CR = (id) => `https://www.crossroadfukuoka.jp/spot/${id}`;

window.SORTIES = {
  /* ---------------- OCTOBRE ---------------- */
  hakataGion: { t: "Balade Hakata–Gion",
    d: "Balade Hakata–Gion : Kushida-jinja, Hakatamachiya Furusatokan, Tocho-ji, Shofuku-ji",
    info: "Tout se fait à pied depuis la station Gion",
    p: [["Kushida-jinja", "櫛田神社 福岡", { w: CR(12510) }], ["Hakatamachiya Furusatokan", "博多町家ふるさと館"], ["Tocho-ji", "東長寺 福岡"], ["Shofuku-ji", "聖福寺 福岡"]] },
  kurume: { t: "Kurume", full: true, city: "Kurume", out: ["lunch", "dinner"],
    d: "Kurume : Suitengu et Bairin-ji, ramen chez Taiho Ramen (maison mère), ruines du château et musée Arima, jardin Ishibashi, Henjo-in, sanctuaire Kora Taisha. Le soir : yakitori à Hiyoshimaru ou Torisuke (ouverts dès 17h)",
    info: "Aller en JR local (870 yens), retour en Nishitetsu depuis Nishitetsu-Kurume (environ 700 yens). Kora Taisha en bus. Budget repas : environ 1 000 à midi, 2 000 à 3 000 le soir",
    alerts: [
      "Le musée Arima est fermé le mardi : aujourd'hui, seulement les ruines du château.",
      "Kora Taisha : le bus s'arrête à « Mii-machi » (御井町), puis environ 30 min de montée à pied (d'après l'office de tourisme de Kurume).",
    ],
    steps: [
      { t: "Train JR local depuis Hakata", info: "870 yens, avec la SUGOCA",
        p: [["Gare JR de Kurume", "JR久留米駅"]] },
      { t: "Suitengu, puis Bairin-ji", info: "À 5 min à pied de la gare JR de Kurume, entrée gratuite",
        p: [["Suitengu", "水天宮 久留米", { w: "https://suitengu.net/" }], ["Bairin-ji", "梅林寺 久留米", { a: "久留米市京町209", w: "https://welcome-kurume.com/spots/detail/4ec3b2dd-9c8e-49e5-86bc-3075af7d95b4" }]] },
      { t: "Ruines du château de Kurume et musée Arima", info: "Environ 20 min à pied, vers le nord",
        p: [["Ruines du château de Kurume", "久留米城跡"], ["Musée Arima (Arima Kinenkan)", "有馬記念館 久留米", { a: "久留米市篠山町444 · 10h–17h, fermé le mardi · 210 yens", w: "https://welcome-kurume.com/spots/detail/73353a67-26a4-4a5a-a5f1-ebcd5fdbbed9" }]] },
      { t: "Henjo-in, le jardin traditionnel", info: "Gratuit. Le quartier Teramachi est sur le chemin vers le resto",
        p: [["Jardin de Henjo-in", "遍照院 久留米", { a: "久留米市寺町56 · 9h–17h, tous les jours", w: "https://welcome-kurume.com/spots/detail/6720d7d9-9dfd-4205-a7dc-55100d45c757" }]] },
      { t: "Déjeuner : Taiho Ramen, la maison mère", info: "Moins de 1 000 yens. Prends le « mukashi ramen ». Espèces ou PayPay",
        p: [["Taiho Ramen, honten", "大砲ラーメン 本店 久留米", { a: "久留米市通外町11-8 · fermé seulement le 1er janvier", w: "https://www.taiho.net/" }]] },
      { t: "Centre culturel Ishibashi (jardins, musée)", info: "Environ 15 min à pied ou en bus",
        p: [["Centre culturel Ishibashi", "石橋文化センター 久留米", { a: "久留米市野中町1015 · musée 10h–17h, fermé le lundi", w: "https://www.ishibashi-bunka.jp/kcam/visit/" }]] },
      { t: "Kora Taisha", info: "Bus Nishitetsu depuis la gare Nishitetsu-Kurume. Vue sur toute la plaine. Vise le bus du retour avant la nuit",
        p: [["Gare Nishitetsu-Kurume (bus)", "西鉄久留米駅"], ["Kora Taisha", "高良大社 久留米", { a: "久留米市御井町1", w: "https://welcome-kurume.com/spots/detail/8b8be88c-7e83-4b47-ad84-382e5d64b622" }]] },
      { t: "Yakitori à Hiyoshimaru ou Torisuke", info: "Ouverts dès 17h, près de la gare Nishitetsu-Kurume",
        p: [["Hiyoshimaru", "日吉丸 焼き鳥 久留米"], ["Torisuke", "鳥佐 焼き鳥 久留米"]] },
      { t: "Retour en train Nishitetsu jusqu'à Tenjin", info: "Environ 700 yens",
        p: [["Gare Nishitetsu-Kurume", "西鉄久留米駅"], ["Gare Nishitetsu-Fukuoka (Tenjin)", "西鉄福岡（天神）駅"]] },
    ],
    p: [] },
  yutoku: { t: "Yutoku Inari & Hizen-Hamashuku", full: true, city: "Kashima (Saga)", out: ["lunch"],
    d: "Yutoku Inari-jinja (grand sanctuaire sur pilotis), puis la rue des brasseries de saké de Hizen-Hamashuku. Alternative : match d'Avispa Fukuoka contre Okayama à 15h",
    info: "Exception JR : train jusqu'à Hizen-Kashima, puis bus d'environ 10 min. Hizen-Hama est à une gare de là",
    p: [["Yutoku Inari-jinja", "祐徳稲荷神社", { w: "https://www.city.saga-kashima.lg.jp/main/323.html" }], ["Hizen-Hamashuku", "肥前浜宿"], ["Avispa Fukuoka (billets)", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  nokonoshima: { t: "Île de Nokonoshima",
    d: "Île de Nokonoshima (cosmos)",
    info: "Métro ou bus jusqu'à Meinohama, puis ferry d'environ 10 min",
    p: [["Embarcadère de Meinohama", "姪浜渡船場"], ["Nokonoshima Island Park", "のこのしまアイランドパーク", { w: "https://nokonoshima.com/" }]] },
  ohori: { t: "Parc Ohori & musée d'art",
    d: "Parc Ohori et musée d'art de Fukuoka (métro jusqu'à Ohorikoen)",
    p: [["Parc Ohori", "大濠公園 福岡"], ["Musée d'art de Fukuoka", "福岡市美術館", { w: "https://www.fukuoka-art-museum.jp/en/" }]] },
  uminonakamichi: { t: "Uminonakamichi & Marine World", full: true,
    d: "Uminonakamichi Seaside Park (cosmos) et aquarium Marine World",
    info: "Ferry depuis Bayside Place à l'aller, train JR ligne Kashii au retour",
    p: [["Bayside Place (ferry)", "ベイサイドプレイス博多"], ["Uminonakamichi Seaside Park", "国営海の中道海浜公園", { w: CR(12408) }], ["Marine World", "マリンワールド海の中道", { w: "https://marine-world.jp/" }]] },
  itoshimaMer: { t: "Itoshima côté mer", full: true, city: "Itoshima", out: ["lunch"],
    d: "Itoshima côté mer : Sakurai Futamigaura (torii dans la mer), cafés en bord de plage, coucher de soleil",
    info: "Bus direct « West Coast Liner » (Showa) depuis Hakata ou Tenjin, environ 55 min jusqu'à Futamigaura. Vérifie l'heure du dernier bus retour",
    p: [["Sakurai Futamigaura", "桜井二見ヶ浦"], ["Arrêt de bus Futamigaura", "二見ヶ浦 バス停 糸島"]] },
  munakata: { t: "Munakata Taisha & Miyajidake", full: true, city: "Munakata", out: ["lunch"],
    d: "Munakata Taisha, puis Miyajidake : « chemin de lumière » au coucher du soleil (arriver vers 14h pour les places gratuites)",
    info: "Exception JR : train jusqu'à Togo, puis bus pour Munakata Taisha. Ensuite JR jusqu'à Fukuma et bus jusqu'à Miyajidake. Retour direct à Tenjin avec le bus Nishitetsu 26A",
    p: [["Munakata Taisha", "宗像大社 辺津宮", { w: "https://munakata-taisha.or.jp/" }], ["Miyajidake-jinja", "宮地嶽神社", { w: "https://www.miyajidake.or.jp/" }], ["Arrêt Miyajidake-jinja-mae (bus 26A)", "宮地嶽神社前 バス停"]] },
  nanzoin: { t: "Nanzoin, le Bouddha couché",
    d: "Nanzoin, le Bouddha couché (Sasaguri). Exception JR, environ 25 min",
    p: [["Nanzoin", "南蔵院 篠栗", { w: "https://www.crossroadfukuoka.jp/spot/11999" }]] },
  kagoshima: { t: "Kagoshima", full: true, city: "Kagoshima", out: ["lunch", "dinner"],
    d: "Kagoshima : ferry pour le volcan Sakurajima, jardin Sengan-en",
    info: "Exception JR : Shinkansen, environ 1h20 (environ 11 400 yens l'aller). Partir vers 7h30",
    p: [["Ferry de Sakurajima", "桜島フェリーターミナル 鹿児島", { w: "https://www.city.kagoshima.lg.jp/sakurajima-ferry/howtouse/hajimete.html" }], ["Sengan-en", "仙巌園", { w: "https://www.kagoshima-yokanavi.jp/spot/10006" }]] },
  atago: { t: "Atago-jinja & plage de Momochi",
    d: "Atago-jinja (vue sur la baie) et plage de Momochi",
    p: [["Atago-jinja", "愛宕神社 福岡"], ["Plage de Momochi", "シーサイドももち海浜公園"]] },
  dazaifu: { t: "Dazaifu Tenmangu", full: true, city: "Dazaifu", out: ["lunch"],
    d: "Dazaifu Tenmangu et la rue commerçante (umegae mochi)",
    info: "Train Nishitetsu, environ 40 min",
    p: [["Dazaifu Tenmangu", "太宰府天満宮", { w: "https://www.dazaifutenmangu.or.jp/" }], ["Rue commerçante (sando)", "太宰府天満宮 参道"], ["Gare Nishitetsu-Dazaifu", "西鉄太宰府駅"]] },
  nagasaki1: { t: "Nagasaki, jour 1", full: true, city: "Nagasaki", night: "Nagasaki", out: ["lunch", "dinner"], pass: "SUNQ · jour 1",
    d: "SUNQ jour 1 – Nagasaki, jour 1 : parc de la Paix, musée de la Bombe atomique, jardin Glover, église d'Oura, Dejima. Le soir : vue depuis le mont Inasa",
    info: "Bus express « Kyushu-go » depuis Tenjin, environ 2h30 (environ 2 900 yens l'aller sans pass)",
    p: [["Terminal de bus de Tenjin", "西鉄天神高速バスターミナル"], ["Parc de la Paix", "平和公園 長崎"], ["Musée de la Bombe atomique", "長崎原爆資料館"], ["Jardin Glover", "グラバー園"], ["Église d'Oura", "大浦天主堂"], ["Dejima", "出島 長崎"], ["Mont Inasa (téléphérique)", "稲佐山ロープウェイ"]] },
  nagasaki2: { t: "Nagasaki, jour 2", full: true, city: "Nagasaki", out: ["breakfast", "lunch", "dinner"], pass: "SUNQ · jour 2",
    d: "SUNQ jour 2 – Nagasaki, jour 2 : croisière Gunkanjima le matin, pont Megane, Sofuku-ji, quartier chinois. Goûter le champon. Au retour, arrêt au bus « Ureshino » pour un bain et le tofu cuit à l'eau thermale",
    info: "Le débarquement dépend de la météo",
    p: [["Croisière Gunkanjima (Yamasa)", "やまさ海運 軍艦島", { w: "https://www.gunkan-jima.net/" }], ["Croisière Gunkanjima (Black Diamond)", "軍艦島上陸クルーズ 長崎", { w: "https://www.gunkanjima-cruise.jp/en/" }], ["Pont Megane", "眼鏡橋 長崎"], ["Sofuku-ji", "崇福寺 長崎"], ["Quartier chinois", "長崎新地中華街"], ["Ureshino Onsen", "嬉野温泉"]] },
  kumamoto: { t: "Kumamoto", full: true, city: "Kumamoto", out: ["lunch"], pass: "SUNQ · jour 3",
    d: "SUNQ jour 3 – Kumamoto : château, rue Sakuranobaba, jardin Suizenji",
    info: "Bus express « Hinokuni-go » depuis Tenjin, environ 2h (environ 2 500 yens l'aller sans pass). Le tram de Kumamoto n'est pas couvert par le SUNQ",
    p: [["Château de Kumamoto", "熊本城"], ["Sakuranobaba Josaien", "桜の馬場 城彩苑"], ["Jardin Suizenji", "水前寺成趣園", { w: "https://www.suizenji.or.jp/" }]] },
  takeo: { t: "Takeo-Onsen", city: "Takeo",
    d: "Après le kick : Takeo-Onsen (bains, bibliothèque, camphrier géant). Exception JR, environ 1h",
    p: [["Takeo-Onsen", "武雄温泉 楼門", { w: "https://www.takeo-kk.net/" }], ["Bibliothèque de Takeo", "武雄市図書館", { w: "https://www.takeo-kk.net/sightseeing/001297.php" }], ["Camphrier de Takeo", "武雄の大楠"]] },
  hakozaki: { t: "Hakozaki-gu & musée d'art asiatique",
    d: "Hakozaki-gu et musée d'art asiatique",
    info: "Métro",
    p: [["Hakozaki-gu", "筥崎宮"], ["Musée d'art asiatique", "福岡アジア美術館", { w: "https://faam.city.fukuoka.lg.jp/" }]] },
  avispaGamba: { t: "Avispa Fukuoka – Gamba Osaka", evening: true, out: ["dinner"],
    d: "Le soir : match d'Avispa Fukuoka contre Gamba Osaka à 19h (stade Best Denka, bus depuis Hakata)",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  maizuru: { t: "Maizuru, Ohori, Daimyo & Yakuin",
    d: "Parc Maizuru (ruines du château), parc Ohori et musée d'art de Fukuoka juste à côté, puis cafés et friperies de Daimyo et Yakuin",
    p: [["Parc Maizuru", "舞鶴公園 福岡城跡"], ["Parc Ohori", "大濠公園 福岡"], ["Musée d'art de Fukuoka", "福岡市美術館", { w: "https://www.fukuoka-art-museum.jp/en/" }], ["Daimyo", "大名 福岡市中央区"], ["Yakuin", "薬院駅"]] },
  uminonakamichi2: { t: "Uminonakamichi & Marine World", full: true,
    d: "Uminonakamichi Seaside Park (cosmos, kochias rouges) et aquarium Marine World. Le soir, si tu as de l'énergie : Hakata Okunchi à Kushida-jinja",
    info: "Ferry depuis Bayside Place à l'aller, retour en ferry aussi. Okunchi : dates à vérifier",
    p: [["Bayside Place (ferry)", "ベイサイドプレイス博多"], ["Uminonakamichi Seaside Park", "国営海の中道海浜公園", { w: "https://www.crossroadfukuoka.jp/spot/12408" }], ["Marine World", "マリンワールド海の中道", { w: "https://marine-world.jp/" }], ["Kushida-jinja", "櫛田神社 福岡", { w: "https://www.crossroadfukuoka.jp/spot/12510" }]] },
  yameUkiha: { t: "Yame & Ukiha", full: true, city: "Yame", out: ["lunch"],
    d: "Yame le matin (quartier des artisans, Konomi Honke), puis Ukiha l'après-midi (quartier Shirakabe, sanctuaire aux 91 torii)",
    info: "Exception JR : jusqu'à Hainuzuka puis bus pour Yame. Ukiha : retour vers Kurume, puis ligne JR Kyudai",
    p: [["Yame Fukushima (quartier des artisans)", "八女福島 白壁の町並み"],
      ["Konomi Honke", "矢部屋許斐本家 八女", { a: "福岡県八女市本町126 · 9h–18h, fermé le dimanche", w: "https://www.konomien.jp/" }],
      ["Ukiha, quartier Shirakabe", "筑後吉井 白壁の町並み"], ["Ukiha Inari-jinja (91 torii)", "浮羽稲荷神社"]] },
  hiko: { t: "Mont Hiko", full: true, city: "Soeda", out: ["lunch"],
    d: "Mont Hiko : funiculaire, sanctuaire, descente à pied",
    info: "Exception JR : jusqu'à Soeda, bus BRT Hikoboshi, puis bus local. Environ 2h30 par trajet : partir tôt",
    p: [["Funiculaire du mont Hiko", "英彦山スロープカー", { w: "https://hikosan-slopecar.net/" }], ["Hikosan-jingu", "英彦山神宮"]] },
  prepTokyo: { t: "Préparer Tokyo", d: "Préparer Tokyo", p: [] },

  /* ---------------- NOVEMBRE ---------------- */
  retourTokyo: { t: "Libre (retour de Tokyo)", d: "Libre (retour de Tokyo)", p: [] },
  asaGeiko: { t: "Asa-geiko à Sumiyoshi-jinja", morning: true, out: ["breakfast"],
    d: "Asa-geiko à Sumiyoshi-jinja (7h–9h), puis petit-déjeuner au marché Yanagibashi (environ 15 min à pied)",
    info: "Entraînement de sumo gratuit, à environ 15 min à pied de la gare de Hakata. Rester silencieux et ne pas parler au maître d'écurie",
    p: [["Sumiyoshi-jinja", "住吉神社 福岡"], ["Marché Yanagibashi", "柳橋連合市場", { a: "福岡市中央区春吉1-6-1", w: "https://yanagibashi-rengo.net/" }]] },
  yobukoKaratsu: { t: "Yobuko & Karatsu", full: true, city: "Karatsu", out: ["lunch"],
    d: "Yobuko (marché du matin, calamar), puis Karatsu (château, pinède Niji no Matsubara)",
    info: "Bus express Showa « Karatsu-go » depuis Hakata ou Tenjin (environ 1h15, environ 1 100 yens), puis bus Showa jusqu'à Yobuko. Le marché ferme vers midi : partir tôt. Alternative : match d'Avispa Fukuoka contre Nagasaki à 15h",
    p: [["Marché du matin de Yobuko", "呼子朝市", { a: "唐津市呼子町呼子 朝市通り · 7h30–12h", w: "https://www.karatsu-kankou.jp/spots/detail/52/" }], ["Château de Karatsu", "唐津城", { w: "https://www.karatsu-kankou.jp/spots/detail/181/" }], ["Niji no Matsubara", "虹の松原"], ["Avispa Fukuoka (billets)", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  arita: { t: "Arita & Mifuneyama illuminé", full: true, city: "Arita", out: ["lunch", "dinner"],
    d: "Arita (village de la porcelaine), puis Mifuneyama illuminé le soir",
    info: "Exception JR : jusqu'à Takeo-Onsen, Arita à 20 min en train. Mifuneyama : bus ou 30 min à pied",
    p: [["Arita, quartier Uchiyama", "有田 内山地区"], ["Mifuneyama Rakuen", "御船山楽園", { w: "https://www.mifuneyamarakuen.jp/en/" }]] },
  tower: { t: "Fukuoka Tower & musée de la ville",
    d: "Fukuoka Tower et musée de la ville de Fukuoka",
    info: "Bus depuis Tenjin",
    p: [["Fukuoka Tower", "福岡タワー", { w: "https://www.fukuokatower.co.jp/" }], ["Musée de la ville de Fukuoka", "福岡市博物館", { w: "https://museum.city.fukuoka.jp/" }]] },
  ainoshima: { t: "Ainoshima, l'île aux chats", full: true,
    d: "Ainoshima, l'île aux chats. Train Nishitetsu jusqu'à Nishitetsu-Shingu, environ 15 min à pied jusqu'au port, puis ferry d'environ 20 min",
    p: [["Port de Shingu (ferry)", "新宮港 福岡", { w: "https://www.town.shingu.fukuoka.jp/soshiki/sangyo_shinko/8/1/2/1844.html" }], ["Ainoshima", "相島 新宮町"]] },
  kashii: { t: "Kashii-gu",
    d: "Kashii-gu",
    info: "Train Nishitetsu (ligne Kaizuka) jusqu'à Nishitetsu-Kashii-Miyamae",
    p: [["Kashii-gu", "香椎宮", { w: "https://www.crossroadfukuoka.jp/spot/12512" }], ["Gare Nishitetsu-Kashii-Miyamae", "西鉄香椎宮前駅"]] },
  shikanoshima: { t: "Shikanoshima", out: ["lunch"],
    d: "Shikanoshima : ferry depuis Bayside Place (environ 30 min), tour de l'île à pied, fruits de mer",
    p: [["Bayside Place (ferry)", "ベイサイドプレイス博多", { w: "https://www.city.fukuoka.lg.jp/kowan/kyakusen/hakata-port/ferry_city.html" }], ["Shikanoshima", "志賀島"]] },
  asaGeiko2: { t: "Asa-geiko de l'écurie Takasago", morning: true,
    d: "Asa-geiko gratuit de l'écurie Takasago au temple Jodo-ji (métro Tojinmachi, 3 min à pied), vers 8h",
    p: [["Temple Jodo-ji (Tojinmachi)", "浄土寺 福岡市中央区 唐人町"]] },
  shofuen: { t: "Shofuen & Rakusuien",
    d: "Shofuen et Rakusuien (matcha, début des couleurs)",
    info: "Shofuen à pied depuis Yakuin, Rakusuien à pied depuis la gare de Hakata",
    p: [["Shofuen", "松風園 福岡", { w: "https://fukuoka-teien.com/" }], ["Rakusuien", "楽水園 福岡", { w: "https://fukuoka-teien.com/" }]] },
  hita: { t: "Hita", full: true, city: "Hita", out: ["lunch"],
    d: "Hita : quartier historique Mameda-machi et sa brasserie de saké",
    info: "Bus express depuis Hakata, environ 1h20",
    p: [["Mameda-machi", "豆田町 日田", { w: "http://www.hita-mameda.jp/" }]] },
  akizuki: { t: "Akizuki & Nyoirin-ji", full: true, city: "Asakura", out: ["lunch"],
    d: "Akizuki (érables), puis Nyoirin-ji, le temple aux grenouilles",
    info: "Train Nishitetsu ligne Amagi jusqu'à Amagi, puis bus d'environ 20 min. Nyoirin-ji au retour, à pied depuis une gare d'Ogori (vérifie l'itinéraire)",
    p: [["Akizuki", "秋月城跡 杉の馬場", { w: "https://amagiasakura.net/" }], ["Nyoirin-ji", "如意輪寺 小郡"]] },
  yusentei: { t: "Jardin Yusentei",
    d: "Jardin Yusentei (érables, matcha)",
    p: [["Yusentei", "友泉亭公園", { w: "https://yusentei.fukuoka-teien.com/" }]] },
  dazaifu2: { t: "Komyozen-ji & Kamado-jinja", full: true, city: "Dazaifu", out: ["lunch"],
    d: "Dazaifu : Komyozen-ji, puis Kamado-jinja",
    info: "Bus entre les deux. Journée dense : choisir l'un des deux si besoin",
    p: [["Komyozen-ji", "光明禅寺 太宰府", { w: "https://www.city.dazaifu.lg.jp/site/kanko/1697.html" }], ["Kamado-jinja", "竈門神社 太宰府"]] },
  ohoriJardin: { t: "Jardin japonais du parc Ohori",
    d: "Jardin japonais du parc Ohori (érables)",
    p: [["Jardin japonais d'Ohori", "大濠公園日本庭園"]] },
  kokura: { t: "Kawachi Fujien & Kokura", full: true, city: "Kitakyushu", out: ["lunch"],
    d: "Kokura : château et marché Tanga. Bus express Nishitetsu depuis Tenjin, environ 1h30 (environ 1 350 yens). Le matin : Kawachi Fujien (érables), exception JR jusqu'à Yahata puis bus",
    p: [["Kawachi Fujien", "河内藤園", { w: "https://www.crossroadfukuoka.jp/spot/13153" }], ["Château de Kokura", "小倉城"], ["Marché Tanga", "旦過市場", { w: "https://www.tangaichiba.jp/" }]] },
  hiroshima1: { t: "Hiroshima, jour 1", full: true, city: "Hiroshima", night: "Hiroshima", out: ["lunch", "dinner"],
    d: "Week-end Hiroshima, jour 1 : parc du Mémorial de la Paix, musée, Dôme de Genbaku, jardin Shukkeien. Le soir : okonomiyaki",
    info: "Bus express « Kofuku Liner » depuis le terminal de bus de Hakata, environ 4h45 (environ 4 500 à 4 800 yens l'aller). Partir tôt",
    p: [["Terminal de bus de Hakata", "博多バスターミナル"], ["Parc du Mémorial de la Paix", "広島平和記念公園"], ["Musée du Mémorial de la Paix", "広島平和記念資料館", { w: "https://hpmmuseum.jp/" }], ["Dôme de Genbaku", "原爆ドーム"], ["Jardin Shukkeien", "縮景園"]] },
  hiroshima2: { t: "Miyajima", full: true, city: "Hiroshima", out: ["breakfast", "lunch", "dinner"],
    d: "Hiroshima, jour 2 : Miyajima, sanctuaire d'Itsukushima, mont Misen, vallon Momijidani. Goûter les huîtres",
    info: "Taxe d'entrée sur l'île à prévoir",
    p: [["Embarcadère de Miyajimaguchi", "宮島口桟橋"], ["Sanctuaire d'Itsukushima", "嚴島神社", { w: "https://www.itsukushimajinja.jp/" }], ["Téléphérique du mont Misen", "宮島ロープウエー", { w: "https://miyajima-ropeway.info/" }], ["Momijidani", "紅葉谷公園 宮島", { w: "https://www.miyajima.or.jp/sightseeing/sightseeing02.html" }]] },
  noelTenjin: { t: "Repos, marché de Noël de Tenjin", evening: true,
    d: "Repos. Le soir : marché de Noël de Tenjin et illuminations de Nakasu",
    p: [["Marché de Noël de Tenjin (Christmas Advent)", "福岡市役所 ふれあい広場", { a: "Place de l'hôtel de ville, 福岡市中央区天神1-8-1", w: "https://christmas-advent.jp/" }], ["Nakasu", "中洲 福岡"]] },
  minami: { t: "Parc Minami",
    d: "Parc Minami (zoo et jardin botanique)",
    info: "Bus depuis Tenjin",
    p: [["Zoo et jardin botanique de Fukuoka", "福岡市動植物園"]] },
  avispaMarinos: { t: "Avispa – Yokohama F. Marinos", evening: true, out: ["dinner"],
    d: "Libre. Le soir : match d'Avispa Fukuoka contre Yokohama F. Marinos à 19h, puis marché de Noël de la gare de Hakata",
    info: "Ouvert jusqu'à 23h en 2025",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }], ["Marché de Noël de la gare de Hakata", "JR博多シティ 駅前広場", { a: "Place devant la gare JR Hakata, 福岡市博多区博多駅中央街1-1", w: "https://christmas-advent.jp/map/" }]] },
  saga: { t: "Saga", city: "Saga", out: ["lunch"],
    d: "Saga : château et musée du château de Saga (bus express « Wakakusu-go » depuis Tenjin, environ 1 100 yens l'aller)",
    p: [["Terminal de bus de Tenjin", "西鉄天神高速バスターミナル"], ["Musée du château de Saga", "佐賀城本丸歴史館", { w: "https://saga-museum.jp/sagajou/" }]] },
  iki: { t: "Île d'Iki", full: true, city: "Iki", out: ["lunch"],
    d: "Île d'Iki en jetfoil depuis le port de Hakata (environ 1h10), puis bus sur l'île. Vérifier la météo et l'heure du dernier bateau",
    p: [["Jetfoil Kyushu Yusen (port de Hakata)", "博多ふ頭 第2ターミナル", { w: "https://www.kyu-you.co.jp/jyosenguide/iki.html" }], ["Île d'Iki", "壱岐島"]] },
  itoshimaMont: { t: "Itoshima côté montagne", full: true, city: "Itoshima", out: ["lunch"],
    d: "Itoshima côté montagne : Sennyo-ji et cascade Shiraito (érables). Alternative : basket, Rizing Zephyr Fukuoka à 14h05",
    info: "Exception JR : jusqu'à Chikuzen-Maebaru, puis bus communautaire d'Itoshima (très peu de bus, vérifie les horaires)",
    p: [["Sennyo-ji Daihio-in", "雷山千如寺大悲王院", { w: "https://www.crossroadfukuoka.jp/spot/12260" }], ["Cascade Shiraito", "白糸の滝 糸島"], ["Rizing Zephyr Fukuoka (billets)", "照葉積水ハウスアリーナ", { w: "https://r-zephyr.com/" }]] },
  mojiko: { t: "Mojiko Retro & Shimonoseki", full: true, city: "Kitakyushu", out: ["lunch"],
    d: "Kitakyushu : Mojiko Retro, tunnel piéton jusqu'à Shimonoseki, marché Karato (sushis le week-end), sanctuaire Akama",
    info: "Bus express « Fukufuku-go » jusqu'à Shimonoseki (environ 1 700 yens), marché Karato, puis ferry Kanmon vers Mojiko. Retour : bus jusqu'à Kokura, puis bus express jusqu'à Tenjin",
    p: [["Marché Karato", "唐戸市場", { a: "山口県下関市唐戸町5-50 · sushis ven.–sam. dès 8h, dim. dès 7h", w: "https://www.karatoichiba.com/" }], ["Sanctuaire Akama", "赤間神宮"], ["Ferry Kanmon (Karato → Mojiko)", "関門汽船 唐戸桟橋"], ["Mojiko Retro", "門司港レトロ", { w: "https://www.mojiko.info/" }], ["Tunnel piéton du Kanmon", "関門トンネル人道 門司側"]] },
  /* ---------------- DÉCEMBRE ---------------- */
  nakasuYatai: { t: "Illuminations de Nakasu & yatai", evening: true, out: ["dinner"],
    d: "Le soir : illuminations de Nakasu et dîner dans un yatai",
    p: [["Yatai de Nakasu", "中洲屋台", { a: "Au bord de la rivière Naka, 福岡市博多区中洲1丁目" }]] },
  canal: { t: "Canal City & Ramen Stadium", out: ["dinner"],
    d: "Canal City (illuminations) et Ramen Stadium",
    info: "À pied depuis Hakata",
    p: [["Canal City Hakata", "キャナルシティ博多", { w: "https://canalcity.co.jp/" }], ["Ramen Stadium", "キャナルシティ ラーメンスタジアム", { a: "福岡市博多区住吉1-2, Center Walk 5e étage · 11h–23h", w: "https://canalcity.co.jp/ra_sta/" }]] },
  recup: { t: "Libre (récupération)", full: true, d: "Libre (récupération)", p: [] },
  kawabata: { t: "Kawabata & artisanat de Hakata",
    d: "Galerie marchande Kawabata et centre d'artisanat de Hakata (Hakata Dento Kogeikan), à pied depuis Nakasu-Kawabata",
    p: [["Galerie Kawabata", "川端通商店街"], ["Hakata Dento Kogeikan", "博多伝統工芸館"]] },
  kakigoya: { t: "Itoshima, cabane à huîtres", full: true, city: "Itoshima", out: ["lunch", "dinner"],
    d: "Itoshima : déjeuner dans une cabane à huîtres (kaki-goya). Bus Showa depuis Tenjin, itinéraire et horaires à vérifier sur Google Maps (option « bus uniquement »). Le soir après le travail : motsunabe au restaurant",
    p: [] },
  yanagawa: { t: "Yanagawa", full: true, city: "Yanagawa", out: ["lunch"],
    d: "Yanagawa : barque avec kotatsu, puis anguille (unagi seiro-mushi)",
    info: "Train Nishitetsu direct depuis Tenjin, environ 50 min",
    p: [["Promenade en barque", "柳川 川下り", { w: "https://kawakudari.com/course_regular" }]] },
  marathon: { t: "Marathon international de Fukuoka",
    d: "Marathon international de Fukuoka (gratuit) : départ à 12h10 au stade Heiwadai, dans le parc Maizuru. Ensuite, balade au parc Ohori",
    info: "Métro jusqu'à Ohorikoen ou Akasaka. Coureurs d'élite, ambiance au bord de la route",
    p: [["Stade Heiwadai", "平和台陸上競技場"], ["Parc Ohori", "大濠公園 福岡"]] },
  futsukaichi: { t: "Onsen de Futsukaichi",
    d: "Onsen de Futsukaichi (train Nishitetsu jusqu'à Nishitetsu-Futsukaichi, puis environ 15 min à pied)",
    p: [["Gare Nishitetsu-Futsukaichi", "西鉄二日市駅"], ["Futsukaichi Onsen", "二日市温泉"]] },
  yoshinogari: { t: "Yoshinogari", full: true, city: "Yoshinogari", out: ["lunch"],
    d: "Site préhistorique de Yoshinogari. Exception JR jusqu'à Yoshinogari-koen, environ 1h",
    p: [["Parc historique de Yoshinogari", "吉野ヶ里歴史公園", { w: "https://www.pref.saga.lg.jp/kiji00313455/index.html" }]] },
  hanamidori: { t: "Mizutaki chez Hanamidori", out: ["dinner"],
    d: "Mizutaki chez Hanamidori (déjeuner tardif ou soir)",
    p: [["Hanamidori, Hakata Ekimae", "博多華味鳥 博多駅前店", { a: "福岡市博多区博多駅前3-23-17, 第2福岡ONビル 1F · midi et soir", w: "https://www.hanamidori.net/stores/0924321801/" }],
      ["Hanamidori, Nakasu (maison mère)", "博多華味鳥 中洲本店", { a: "福岡市博多区中洲5-4-24, トリゼンビル · midi et soir", w: "https://www.hanamidori.net/stores/0922630322/" }]] },
  daimyoNoel: { t: "Cafés de Daimyo & marché de Noël",
    d: "Cafés de Daimyo, puis marché de Noël de Tenjin",
    p: [["Daimyo", "大名 福岡市中央区"], ["Marché de Noël de Tenjin (Christmas Advent)", "福岡市役所 ふれあい広場", { a: "Place de l'hôtel de ville, 福岡市中央区天神1-8-1", w: "https://christmas-advent.jp/" }]] },
  huisTenBosch: { t: "Huis Ten Bosch", full: true, city: "Sasebo", out: ["lunch", "dinner"], pass: "SUNQ · jour 1",
    d: "SUNQ jour 1 – Huis Ten Bosch : illuminations d'hiver. Bus express direct depuis Tenjin, environ 2h. Retour tard : à éviter si c'est ta semaine de kick du vendredi soir",
    p: [["Terminal de bus de Tenjin", "西鉄天神高速バスターミナル"], ["Huis Ten Bosch", "ハウステンボス", { w: "https://www.huistenbosch.co.jp/" }]] },
  beppu: { t: "Beppu", full: true, city: "Beppu", night: "Beppu", out: ["lunch", "dinner"], pass: "SUNQ · jour 2",
    d: "SUNQ jour 2 – Beppu : les « enfers » de Beppu, bain dans un onsen, nuit sur place",
    info: "Bus express « Toyonokuni-go », environ 2h (3 250 yens l'aller sans pass)",
    p: [["Enfers de Beppu", "別府地獄めぐり 海地獄", { w: "https://www.beppu-jigoku.com/" }]] },
  yufuin: { t: "Yufuin", full: true, city: "Yufuin", out: ["breakfast", "lunch"], pass: "SUNQ · jour 3",
    d: "SUNQ jour 3 – Yufuin : rue Yunotsubo, lac Kinrin, retour en bus express « Yufuin-go »",
    p: [["Rue Yunotsubo", "湯の坪街道"], ["Lac Kinrin", "金鱗湖"], ["Gare routière de Yufuin", "由布院駅前バスセンター"]] },
  kurokawa1: { t: "Kurokawa Onsen", full: true, city: "Kurokawa", night: "Kurokawa", out: ["lunch", "dinner"],
    d: "Kurokawa Onsen : bus direct depuis Tenjin (environ 3h, 3 bus par jour, réservation obligatoire), nuit dans un ryokan",
    p: [["Kurokawa Onsen", "黒川温泉 旅館組合 風の舎", { w: "https://www.kurokawaonsen.or.jp/" }]] },
  kurokawa2: { t: "Kurokawa, les trois bains", full: true, city: "Kurokawa", out: ["breakfast", "lunch"],
    d: "Kurokawa : trois bains avec le pass (nyuto tegata), retour en bus l'après-midi. Le soir : marché de Noël de Tenjin",
    p: [["Pass nyuto tegata", "黒川温泉 旅館組合 風の舎", { w: "https://www.kurokawaonsen.or.jp/tegata/" }], ["Marché de Noël de Tenjin (Christmas Advent)", "福岡市役所 ふれあい広場", { a: "Place de l'hôtel de ville, 福岡市中央区天神1-8-1", w: "https://christmas-advent.jp/" }]] },
  souvenirs: { t: "Achats de souvenirs",
    d: "Achats de souvenirs : mentaiko, artisanat de Hakata",
    p: [["Hakata Dento Kogeikan", "博多伝統工芸館"]] },
  basketKurume: { t: "Basket : Rizing Zephyr – Fukushima", evening: true, city: "Kurume", out: ["dinner"],
    d: "Le soir : basket, Rizing Zephyr Fukuoka contre Fukushima à 19h05, Kurume Arena (environ 2 000 yens au 2e étage)",
    p: [["Kurume Arena", "久留米アリーナ", { w: "https://r-zephyr.com/" }]] },
  avispaShimizu: { t: "Avispa – Shimizu & mont Sarakura", full: true, out: ["dinner"],
    d: "Match d'Avispa Fukuoka contre Shimizu à 14h30 (dernier match à domicile). Le soir : vue depuis le mont Sarakura",
    info: "Stade Best Denka : bus depuis Hakata. Mont Sarakura : exception JR jusqu'à Yahata, navette puis téléphérique",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }], ["Téléphérique du mont Sarakura", "皿倉山ケーブルカー", { w: "https://www.sarakurayama-cablecar.co.jp/timetable/" }]] },
  adieux: { t: "Dernier jour", evening: true, out: ["dinner"],
    d: "Dernier jour : yatai d'adieu à Nakasu et marché de Noël de la gare de Hakata",
    p: [["Yatai de Nakasu", "中洲屋台", { a: "Au bord de la rivière Naka, 福岡市博多区中洲1丁目" }], ["Marché de Noël de la gare de Hakata", "JR博多シティ 駅前広場", { a: "Place devant la gare JR Hakata, 福岡市博多区博多駅中央街1-1", w: "https://christmas-advent.jp/map/" }]] },

  /* ---------------- PLAN B (ta liste « Pour les après-midi libres et les jours de pluie ») ---------------- */
  yanagibashi: { t: "Marché Yanagibashi (le matin)", d: "Marché Yanagibashi (le matin)", b: "Près du centre",
    p: [["Marché Yanagibashi", "柳橋連合市場", { a: "福岡市中央区春吉1-6-1", w: "https://yanagibashi-rengo.net/" }]] },
  sumiyoshi: { t: "Sumiyoshi-jinja", d: "Sumiyoshi-jinja", b: "Près du centre", p: [["Sumiyoshi-jinja", "住吉神社 福岡"]] },
  maizuruB: { t: "Parc Maizuru", d: "Parc Maizuru", b: "Près du centre", p: [["Parc Maizuru", "舞鶴公園 福岡城跡"]] },
  museeAsie: { t: "Musée d'art asiatique", d: "Musée d'art asiatique", b: "Jours de pluie", p: [["Musée d'art asiatique", "福岡アジア美術館", { w: "https://faam.city.fukuoka.lg.jp/" }]] },
  museeArt: { t: "Musée d'art de Fukuoka", d: "Musée d'art de Fukuoka", b: "Jours de pluie", p: [["Musée d'art de Fukuoka", "福岡市美術館", { w: "https://www.fukuoka-art-museum.jp/en/" }]] },
  museeVille: { t: "Musée de la ville", d: "Musée de la ville", b: "Jours de pluie", p: [["Musée de la ville de Fukuoka", "福岡市博物館", { w: "https://museum.city.fukuoka.jp/" }]] },
  museeKyushu: { t: "Musée national de Kyushu", d: "Musée national de Kyushu", b: "Jours de pluie", full: true, p: [["Musée national de Kyushu", "九州国立博物館", { w: "https://www.kyuhaku.jp/" }]] },
  canalPluie: { t: "Canal City", d: "Canal City", b: "Jours de pluie", p: [["Canal City Hakata", "キャナルシティ博多", { w: "https://canalcity.co.jp/" }]] },
  yataiSoir: { t: "Yatai de Nakasu", d: "Yatai de Nakasu", b: "Le soir après le travail", evening: true, out: ["dinner"],
    p: [["Yatai de Nakasu", "中洲屋台", { a: "Au bord de la rivière Naka, 福岡市博多区中洲1丁目" }]] },
  motsunabe: { t: "Motsunabe", d: "Motsunabe", b: "Le soir après le travail", evening: true, out: ["dinner"], p: [] },
  noelSoir: { t: "Marchés de Noël", d: "Marchés de Noël (ouverts jusqu'à 23h en 2025)", b: "Le soir après le travail", evening: true,
    p: [["Marché de Noël de Tenjin (Christmas Advent)", "福岡市役所 ふれあい広場", { a: "Place de l'hôtel de ville, 福岡市中央区天神1-8-1", w: "https://christmas-advent.jp/" }]] },
  avispaOkayama: { t: "Avispa Fukuoka (sam. 10 oct., 15h)", d: "Match d'Avispa Fukuoka (football, J1) au stade Best Denka le sam. 10 oct. à 15h", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  avispaNagasaki: { t: "Avispa Fukuoka (sam. 7 nov., 15h)", d: "Match d'Avispa Fukuoka (football, J1) au stade Best Denka le sam. 7 nov. à 15h", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  avispaDec: { t: "Avispa Fukuoka (dim. 13 déc., 15h)", d: "Match d'Avispa Fukuoka (football, J1) au stade Best Denka le dim. 13 déc. à 15h", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム", { w: "https://www.avispa.co.jp/" }]] },
  basketIsland: { t: "Basket, Rizing Zephyr (sam. 28 nov., 14h05)", d: "Basket avec Rizing Zephyr Fukuoka à Island City, le sam. 28 nov. à 14h05", b: "Sport",
    p: [["Island City", "照葉積水ハウスアリーナ", { w: "https://r-zephyr.com/" }]] },
  shimonosekiB: { t: "Shimonoseki & sanctuaire Akama", d: "Shimonoseki et le sanctuaire Akama", b: "Autres journées en train", full: true,
    p: [["Sanctuaire Akama", "赤間神宮"], ["Marché Karato", "唐戸市場", { a: "山口県下関市唐戸町5-50", w: "https://www.karatoichiba.com/" }]] },
  sagaB: { t: "Saga et son château", d: "La ville de Saga et son château", b: "Autres journées en train", p: [["Musée du château de Saga", "佐賀城本丸歴史館", { w: "https://saga-museum.jp/sagajou/" }]] },
  shikanoshimaB: { t: "Shikanoshima en ferry", d: "Shikanoshima en ferry", b: "Autres journées en train", p: [["Bayside Place (ferry)", "ベイサイドプレイス博多"]] },
};


/* ---------- Mes lieux réguliers ---------- */
window.MY_PLACES = {
  gym: { name: "Anytime Fitness Meinohama", q: "エニタイムフィットネス 姪浜店",
    a: "福岡市西区内浜1-7-3, ウエストコート姪浜レジャービル 2F · 24h/24, accueil 11h–20h",
    w: "https://www.anytimefitness.co.jp/meinohama/" },
  kick: null,
};

/* ---------- Les jours : sport du matin + sorties ----------
   m : kick | salle | journee (sans salle) | weekend | tokyo | repos */
window.DAYS = {
  "2026-10-03": { m: "weekend", s: [] },
  "2026-10-04": { m: "weekend", s: [] },
  "2026-10-05": { m: "kick", s: ["hakataGion"] },
  "2026-10-06": { m: "journee", s: ["kurume"] },
  "2026-10-07": { m: "salle", s: ["nokonoshima"] },
  "2026-10-08": { m: "kick", s: [], note: "Reporté au jeu. 22 oct. (parc Ohori et musée d'art)" },
  "2026-10-09": { m: "journee", s: [], note: "Reporté au ven. 23 oct. (Uminonakamichi et Marine World)" },
  "2026-10-10": { m: "weekend", s: ["yutoku"] },
  "2026-10-11": { m: "weekend", s: ["itoshimaMer"] },
  "2026-10-12": { m: "kick", s: ["atago"], ferie: true },
  "2026-10-13": { m: "journee", s: ["dazaifu"] },
  "2026-10-14": { m: "journee", s: ["munakata"] },
  "2026-10-15": { m: "kick", s: ["nanzoin"] },
  "2026-10-16": { m: "journee", s: ["kagoshima"] },
  "2026-10-17": { m: "weekend", s: ["nagasaki1"] },
  "2026-10-18": { m: "weekend", s: ["nagasaki2"] },
  "2026-10-19": { m: "kick", s: ["takeo"] },
  "2026-10-20": { m: "journee", s: ["kumamoto"] },
  "2026-10-21": { m: "salle", s: ["hakozaki", "avispaGamba"] },
  "2026-10-22": { m: "kick", s: ["maizuru"] },
  "2026-10-23": { m: "journee", s: ["uminonakamichi2"] },
  "2026-10-24": { m: "weekend", s: ["yameUkiha"] },
  "2026-10-25": { m: "weekend", s: ["hiko"] },
  "2026-10-26": { m: "kick", s: ["prepTokyo"] },
  "2026-11-05": { m: "kick", s: ["retourTokyo"] },
  "2026-11-06": { m: "matin", s: ["asaGeiko"] },
  "2026-11-07": { m: "weekend", s: ["yobukoKaratsu"] },
  "2026-11-08": { m: "weekend", s: ["arita"] },
  "2026-11-09": { m: "kick", s: ["tower"] },
  "2026-11-10": { m: "journee", s: ["ainoshima"] },
  "2026-11-11": { m: "salle", s: ["kashii"] },
  "2026-11-12": { m: "kick", s: ["shikanoshima"] },
  "2026-11-13": { m: "matin", s: ["asaGeiko2", "shofuen"] },
  "2026-11-14": { m: "weekend", s: ["hita"] },
  "2026-11-15": { m: "weekend", s: ["akizuki"] },
  "2026-11-16": { m: "kick", s: ["yusentei"] },
  "2026-11-17": { m: "journee", s: ["dazaifu2"] },
  "2026-11-18": { m: "salle", s: ["ohoriJardin"] },
  "2026-11-19": { m: "kick", s: [] },
  "2026-11-20": { m: "journee", s: ["kokura"] },
  "2026-11-21": { m: "weekend", s: ["hiroshima1"] },
  "2026-11-22": { m: "weekend", s: ["hiroshima2"] },
  "2026-11-23": { m: "kick", s: ["noelTenjin"], ferie: true },
  "2026-11-24": { m: "salle", s: ["minami"] },
  "2026-11-25": { m: "salle", s: ["avispaMarinos"] },
  "2026-11-26": { m: "kick", s: ["saga"] },
  "2026-11-27": { m: "journee", s: ["iki"] },
  "2026-11-28": { m: "weekend", s: ["itoshimaMont"] },
  "2026-11-29": { m: "weekend", s: ["mojiko"] },
  "2026-11-30": { m: "kick", s: ["nakasuYatai"] },
  "2026-12-01": { m: "salle", s: ["canal"] },
  "2026-12-02": { m: "journee", s: ["recup"] },
  "2026-12-03": { m: "kick", s: ["kawabata"] },
  "2026-12-04": { m: "journee", s: ["kakigoya"] },
  "2026-12-05": { m: "weekend", s: ["yanagawa"] },
  "2026-12-06": { m: "weekend", s: ["marathon"] },
  "2026-12-07": { m: "kick", s: ["futsukaichi"] },
  "2026-12-08": { m: "journee", s: ["yoshinogari"] },
  "2026-12-09": { m: "salle", s: ["hanamidori"] },
  "2026-12-10": { m: "kick", s: ["daimyoNoel"] },
  "2026-12-11": { m: "journee", s: ["huisTenBosch"] },
  "2026-12-12": { m: "weekend", s: ["beppu"] },
  "2026-12-13": { m: "weekend", s: ["yufuin"] },
  "2026-12-14": { m: "kick", s: [] },
  "2026-12-15": { m: "journee", s: ["kurokawa1"] },
  "2026-12-16": { m: "journee", s: ["kurokawa2"] },
  "2026-12-17": { m: "kick", s: ["souvenirs"] },
  "2026-12-18": { m: "salle", s: ["basketKurume"] },
  "2026-12-19": { m: "weekend", s: ["avispaShimizu"] },
  "2026-12-20": { m: "weekend", s: ["adieux"] },
};

/* ---------- Dates clés 2026 ---------- */
window.EVENTS = [
  { when: "7–9 oct.", from: "2026-10-07", what: "Nagasaki Kunchi", where: "En semaine, non placé. Week-end Nagasaki le 17–18 oct." },
  { when: "10–20 oct.", from: "2026-10-10", what: "Miyajidake, « chemin de lumière »", where: "Mer. 14 oct.", date: "2026-10-14" },
  { when: "12 oct.", from: "2026-10-12", what: "Jour férié (foule partout)", where: "" },
  { when: "23–24 oct.", from: "2026-10-23", what: "Hakata Okunchi, Kushida-jinja (à vérifier)", where: "Ven. 23 oct.", date: "2026-10-23" },
  { when: "30 oct.–3 nov.", from: "2026-10-30", what: "Saga Balloon Fiesta", where: "Raté (Tokyo)", missed: true },
  { when: "31 oct.–3 nov.", from: "2026-10-31", what: "Illuminations des temples de Gion", where: "Raté (Tokyo)", missed: true },
  { when: "2–4 nov.", from: "2026-11-02", what: "Karatsu Kunchi", where: "Raté (Tokyo)", missed: true },
  { when: "Début nov.", from: "2026-11-06", what: "Asa-geiko gratuit à Sumiyoshi-jinja", where: "Ven. 6 nov.", date: "2026-11-06" },
  { when: "8–22 nov.", from: "2026-11-08", what: "Tournoi de sumo de Kyushu : complet", where: "Remplacé par l'asa-geiko gratuit (6 nov.)" },
  { when: "Nov.–25 déc.", from: "2026-11-01", what: "Marchés de Noël", where: "Mer. 25 nov., mer. 16 déc." },
  { when: "23 nov.", from: "2026-11-23", what: "Jour férié", where: "" },
  { when: "6 déc.", from: "2026-12-06", what: "Marathon international de Fukuoka (gratuit)", where: "Dim. 6 déc.", date: "2026-12-06" },
];

/* ---------- À réserver ---------- */
window.BOOKINGS = [
  { id: "sunq1", what: "SUNQ Pass Nord « 3 jours sur 5 » (17, 18 et 20 oct.) + réserver les places des bus express (Nagasaki, Kumamoto)", for: "2026-10-17", cost: "env. 9 500 à 10 000 ¥" },
  { id: "nagasaki", what: "Hôtel à Nagasaki (nuit du 17 oct.) et croisière Gunkanjima", for: "2026-10-17", cost: "hôtel 7 000–12 000 ¥ · croisière 3 600–4 700 ¥ + 650 ¥" },
  { id: "kawachi", what: "Billets Kawachi Fujien pour le 20 nov.", for: "2026-11-20" },
  { id: "hiroshima", what: "Bus « Kofuku Liner » et hôtel à Hiroshima ou Miyajima (nuit du 21 nov.), réserver tôt", for: "2026-11-21", cost: "bus 4 500–4 800 ¥ l'aller" },
  { id: "sunq2", what: "SUNQ Pass Nord 3 jours (11, 12 et 13 déc.) + réserver les places des bus express (Huis Ten Bosch, Beppu)", for: "2026-12-11", cost: "env. 9 500 à 10 000 ¥" },
  { id: "beppu", what: "Hôtel à Beppu ou Yufuin (nuit du 12 déc.)", for: "2026-12-12" },
  { id: "kurokawa", what: "Bus Kurokawa (réservation obligatoire) + ryokan (nuit du 15 déc.)", for: "2026-12-15", cost: "bus 7 500 ¥ A/R avec pass 3 bains · ryokan 20 000–40 000 ¥" },
  { id: "basket", what: "Billets basket du 18 déc. sur le site de Rizing Zephyr Fukuoka", for: "2026-12-18", cost: "~2 000 ¥" },
  { id: "sumo", what: "Sumo pas cher : surveiller la revente officielle au prix d'origine (chaise à l'étage, en semaine). Éviter les sites de revente privés.", for: "2026-11-08" },
];

/* ---------- Infos pratiques ---------- */
window.TRIP_RULES = [
  "Les sorties passent avant la salle. Les jours « Journée, sans salle », tu pars vers 9h et tu rentres avant 17h.",
  "Kick : lundi et jeudi 12h–13h (fixe). La sortie commence après, vers 13h30. Le vendredi soir une semaine sur deux ne gêne rien.",
  "Salle : mardi, mercredi, vendredi 10h–11h30, seulement les jours sans grande sortie.",
  "Travail : 17h/18h–20h, pas obligatoire : une belle sortie passe avant.",
  "Week-end : pas de travail, journées complètes.",
  "Les jours libres servent à souffler.",
];

window.TRANSPORT = [
  "Surtout bus, trains Nishitetsu, métro et marche (JR seulement pour les exceptions). À la campagne, les bus passent rarement : vérifie les horaires la veille (Google Maps ou Navitime) et note l'heure du dernier retour.",
  "SUGOCA (l'équivalent JR Kyushu de la Suica) : au distributeur de n'importe quelle gare JR, touche « IC card » puis « SUGOCA ». 2 000 ¥ dont 500 de caution. Marche partout : trains, métro, bus, supérettes, et à Tokyo. Recharge aux distributeurs ou en supérette.",
  "Garde un peu de monnaie : certains bus de campagne ne prennent que les espèces.",
  "Sans JR, les grands trajets se font en bus express, souvent deux fois moins cher que le train. Les jours marqués « Exception JR » utilisent le train JR.",
];

window.PASSES = [
  { name: "SUNQ Nord « 3 jours sur 5 »", price: "env. 9 500–10 000 ¥", days: "17, 18 et 20 oct.", covers: "Nagasaki, arrêt Ureshino, Kumamoto, bus locaux", without: "env. 11 000 ¥" },
  { name: "SUNQ Nord 3 jours", price: "env. 9 500–10 000 ¥", days: "11, 12 et 13 déc.", covers: "Huis Ten Bosch, Beppu, Yufuin, bus locaux", without: "env. 11 000–12 000 ¥" },
];
window.PASS_NOTES = [
  "SUNQ Pass Nord de Kyushu : le pass bus qui remplace les pass JR. Il donne les bus express et la plupart des bus locaux à volonté dans les préfectures de Fukuoka, Saga, Nagasaki, Kumamoto et Oita, plus Shimonoseki. Les jours marqués « SUNQ » dans le planning l'utilisent.",
  "Acheter : en ligne (version numérique sur le téléphone) ou aux terminaux de bus de Tenjin et de Hakata. Il existe aussi une version « 2 jours sur 3 » à environ 8 000 yens.",
  "Réserver les places des bus express (Nagasaki, Kumamoto, Beppu, Huis Ten Bosch) dès l'achat, c'est gratuit avec le pass.",
  "Non couvert : le bus pour Hiroshima, les trams, le métro et les trains Nishitetsu. Garde ta SUGOCA pour tout ça.",
  "Les prix varient selon le vendeur : compare avant d'acheter.",
];

window.COSTS_NOTE = "Total estimé des sorties sur les 3 mois (hors loyer et courses du quotidien) : environ 195 000 à 215 000 yens pour les transports, les nuits d'hôtel et les entrées, et environ 285 000 à 325 000 yens en comptant les repas pris dehors pendant les sorties.";

window.COSTS = [
  { group: "Transports", rows: [
    ["Carte SUGOCA", "2 000 ¥ une fois", "1 500 de crédit + 500 de caution"],
    ["Métro de Fukuoka", "210–380 ¥", "par trajet, avec la SUGOCA"],
    ["Trains Nishitetsu", "400–900 ¥", "l'aller (Dazaifu, Kurume, Yanagawa, Futsukaichi)"],
    ["Bus Fukuoka – Nagasaki (Kyushu-go)", "~2 900 ¥", "l'aller, couvert par le SUNQ"],
    ["Bus Fukuoka – Kumamoto (Hinokuni-go)", "~2 500 ¥", "l'aller, couvert par le SUNQ"],
    ["Bus Fukuoka – Beppu ou Yufuin", "3 250 ¥", "l'aller, couvert par le SUNQ"],
    ["Bus Hakata – Hiroshima (Kofuku Liner)", "4 500–4 800 ¥", "l'aller, environ 4h45, non couvert"],
    ["Bus vers Kokura, Karatsu, Saga, Shimonoseki", "1 100–1 700 ¥", "l'aller, couverts par le SUNQ"],
    ["Fukuoka – Kurokawa (bus)", "7 500 ¥", "A/R avec le pass 3 bains"],
    ["Hakata – Iki (jetfoil)", "~6 900 ¥", "l'aller"],
  ] },
  { group: "Visites", rows: [
    ["Croisière Gunkanjima", "3 600–4 700 ¥", "+ 650 ¥ en espèces"],
    ["Miyajima", "~2 400 ¥", "taxe, sanctuaire, téléphérique"],
    ["Musées de la Paix", "~200 ¥", ""],
    ["Jardins de Fukuoka", "100–300 ¥", "matcha 500–700 ¥"],
    ["Musée national, château de Kumamoto", "700–800 ¥", ""],
    ["Huis Ten Bosch", "7 000 ¥ et +", "le plus cher"],
    ["Match d'Avispa", "2 000–4 000 ¥", ""],
    ["Asa-geiko, sanctuaires, illuminations", "Gratuit", ""],
  ] },
  { group: "Manger et dormir", rows: [
    ["Bol de ramen", "800–1 200 ¥", ""],
    ["Soirée au yatai", "2 000–3 000 ¥", "souvent en espèces"],
    ["Motsunabe ou mizutaki", "2 000–4 000 ¥", ""],
    ["Cabane à huîtres", "2 000–3 000 ¥", ""],
    ["Anguille à Yanagawa", "4 000–5 000 ¥", ""],
    ["Hôtel simple", "7 000–12 000 ¥", "la nuit, plus cher en novembre"],
    ["Ryokan à Kurokawa", "20 000–40 000 ¥", "avec dîner"],
  ] },
];
