/* =========================================================
   PLANNING DU SÉJOUR — Fukuoka, oct. à déc. 2026
   Rien n'est figé : dans l'app tu peux déplacer, retirer,
   ajouter une sortie ou la marquer comme faite. Ces changements
   restent sur ton téléphone ; ce fichier est le plan de base.

   SORTIES : une entrée par sortie
     t     titre court          d     ce qu'on y fait
     go    comment y aller      tip   à savoir
     full  journée entière (pas de salle ce jour-là)
     morning  occupe la matinée (pas de salle)
     evening  se passe le soir
     city  autre ville          night ville où tu dors
     out   repas pris dehors : breakfast / lunch / dinner
     eat   conseil pour manger dehors
     pass  jour de pass JR
     p     lieux : [nom, recherche Apple Plans]
   ========================================================= */

window.TRIP = {
  start: "2026-10-03",
  end: "2026-12-20",
  tokyo: { from: "2026-10-27", to: "2026-11-04" },
  months: {
    9: { name: "Octobre", theme: "La mer, les fleurs et Nagasaki", intro: "Octobre profite de la douceur : îles, champs de fleurs et la côte d'Itoshima." },
    10: { name: "Novembre", theme: "Les feuillages et Hiroshima", intro: "Les érables sont au plus beau de la mi à la fin novembre. Les jardins de la ville sont placés en semaine, les sites éloignés le week-end." },
    11: { name: "Décembre", theme: "Onsen, illuminations et adieux", intro: "Décembre est plus calme en semaine. Les week-ends vont aux onsen de Beppu et à Kitakyushu." },
  },
};

window.SORTIES = {
  /* ---------------- OCTOBRE ---------------- */
  hakataGion: { t: "Balade Hakata–Gion", d: "Kushida-jinja, Hakatamachiya Furusatokan, Tocho-ji, Shofuku-ji.",
    go: "Tout se fait à pied depuis la station Gion.",
    p: [["Kushida-jinja", "櫛田神社 福岡"], ["Hakatamachiya Furusatokan", "博多町家ふるさと館"], ["Tocho-ji", "東長寺 福岡"], ["Shofuku-ji", "聖福寺 福岡"]] },
  kurume: { t: "Kurume", d: "Ramen, jardin Ishibashi, sanctuaire Kora Taisha.", full: true, city: "Kurume", out: ["lunch"],
    go: "Train local JR (environ 40 min) ou Shinkansen (15 min). Kora Taisha en bus depuis la gare.",
    eat: "Le ramen tonkotsu de Kurume, c'est l'origine du tonkotsu : prends-le sans riz ni gyoza, et ne bois pas tout le bouillon.",
    p: [["Taiho Ramen (honten)", "大砲ラーメン 本店 久留米"], ["Jardin Ishibashi", "石橋文化センター 久留米"], ["Kora Taisha", "高良大社 久留米"]] },
  nokonoshima: { t: "Île de Nokonoshima", d: "Les champs de cosmos de l'Island Park.",
    go: "Métro ou bus jusqu'à Meinohama, puis ferry d'environ 10 min.",
    p: [["Embarcadère de Meinohama", "姪浜渡船場"], ["Nokonoshima Island Park", "のこのしまアイランドパーク"]] },
  ohori: { t: "Parc Ohori & musée d'art", d: "Tour du lac, puis le musée d'art de Fukuoka.",
    go: "Métro jusqu'à Ohorikoen.",
    p: [["Parc Ohori", "大濠公園 福岡"], ["Musée d'art de Fukuoka", "福岡市美術館"]] },
  uminonakamichi: { t: "Uminonakamichi & Marine World", d: "Les cosmos du Seaside Park, puis l'aquarium Marine World.", full: true,
    go: "Ferry depuis Bayside Place à l'aller, train JR ligne Kashii au retour.",
    p: [["Bayside Place (ferry)", "ベイサイドプレイス博多"], ["Uminonakamichi Seaside Park", "国営海の中道海浜公園"], ["Marine World", "マリンワールド海の中道"]] },
  itoshimaMer: { t: "Itoshima côté mer", d: "Sakurai Futamigaura (le torii dans la mer), cafés en bord de plage, coucher de soleil.", full: true, city: "Itoshima", out: ["lunch"],
    go: "Train JR jusqu'à Chikuzen-Maebaru, puis bus Showa. Note l'heure du dernier bus.",
    tip: "Alternative : match d'Avispa Fukuoka contre Okayama à 15h.",
    eat: "Poisson grillé ou kaisendon dans un café du bord de mer.",
    p: [["Gare de Chikuzen-Maebaru", "筑前前原駅"], ["Sakurai Futamigaura", "桜井二見ヶ浦"]] },
  munakata: { t: "Munakata Taisha & Miyajidake", d: "Munakata Taisha, puis Miyajidake pour le coucher de soleil sur le « chemin de lumière ».", full: true, city: "Munakata", out: ["lunch"],
    go: "JR jusqu'à Togo, puis bus pour Munakata. Ensuite JR jusqu'à Fukuma et environ 25 min à pied.",
    tip: "Arrive vers 14h à Miyajidake pour les places gratuites. Beaucoup de monde.",
    eat: "Sashimi ou teishoku de poisson : la côte de Munakata est réputée pour ça.",
    p: [["Munakata Taisha", "宗像大社 辺津宮"], ["Miyajidake-jinja", "宮地嶽神社"]] },
  atago: { t: "Atago-jinja & plage de Momochi", d: "Vue sur la baie depuis le sanctuaire, puis la plage.",
    p: [["Atago-jinja", "愛宕神社 福岡"], ["Plage de Momochi", "シーサイドももち海浜公園"]] },
  dazaifu: { t: "Dazaifu", d: "Dazaifu Tenmangu, musée national de Kyushu, puis les temples Kanzeon-ji et Kaidan-in (10 min à pied).", full: true, city: "Dazaifu", out: ["lunch"],
    go: "Train Nishitetsu, environ 40 min.",
    eat: "Soba ou teishoku dans la rue du sanctuaire. Les umegae-mochi sont sucrés, tu peux passer.",
    p: [["Dazaifu Tenmangu", "太宰府天満宮"], ["Musée national de Kyushu", "九州国立博物館"], ["Kanzeon-ji", "観世音寺 太宰府"], ["Kaidan-in", "戒壇院 太宰府"]] },
  yutoku: { t: "Yutoku Inari & Hizen-Hamashuku", d: "Le grand sanctuaire sur pilotis, puis la rue des brasseries de saké.", full: true, city: "Kashima (Saga)", out: ["lunch"],
    go: "Train JR jusqu'à Hizen-Kashima, puis bus d'environ 10 min. Hizen-Hama est à une gare de là.",
    eat: "Teishoku près du sanctuaire, ou konbini : salad chicken + onigiri.",
    p: [["Yutoku Inari-jinja", "祐徳稲荷神社"], ["Hizen-Hamashuku", "肥前浜宿"]] },
  nanzoin: { t: "Nanzoin, le Bouddha couché", d: "Une des plus grandes statues en bronze du monde, à Sasaguri.",
    go: "Train JR, environ 25 min.",
    p: [["Nanzoin", "南蔵院 篠栗"]] },
  kagoshima: { t: "Kagoshima", d: "Ferry pour le volcan Sakurajima, puis le jardin Sengan-en.", full: true, city: "Kagoshima", out: ["lunch", "dinner"], pass: "Pass Kyushu · jour 1",
    go: "Shinkansen, environ 1h20 : pars vers 7h30. Le ferry pour Sakurajima met environ 15 min.",
    eat: "Kurobuta (porc noir) en shabu-shabu : maigre et local. Le tonkotsu braisé est plus gras, petite portion.",
    p: [["Terminal du ferry de Sakurajima", "桜島フェリーターミナル 鹿児島"], ["Sengan-en", "仙巌園"]] },
  nagasaki1: { t: "Nagasaki, jour 1", d: "Parc de la Paix, musée de la Bombe atomique, jardin Glover, église d'Oura, Dejima. Le soir : vue depuis le mont Inasa.", full: true, city: "Nagasaki", night: "Nagasaki", out: ["lunch", "dinner"], pass: "Pass Kyushu · jour 2",
    go: "Train via Takeo-Onsen, environ 1h20.",
    eat: "Champon : fruits de mer, porc et légumes, une bonne option. Laisse la moitié du bouillon. Le castella est sucré, tu passes.",
    p: [["Parc de la Paix", "平和公園 長崎"], ["Musée de la Bombe atomique", "長崎原爆資料館"], ["Jardin Glover", "グラバー園"], ["Église d'Oura", "大浦天主堂"], ["Dejima", "出島 長崎"], ["Mont Inasa (téléphérique)", "稲佐山ロープウェイ"]] },
  nagasaki2: { t: "Nagasaki, jour 2", d: "Croisière Gunkanjima le matin, pont Megane, Sofuku-ji, quartier chinois. Goûter le champon.", full: true, city: "Nagasaki", out: ["breakfast", "lunch", "dinner"], pass: "Pass Kyushu · jour 3",
    tip: "Le débarquement sur Gunkanjima dépend de la météo. Droit d'accès à l'île en espèces.",
    eat: "Petit-déj d'hôtel : œufs, poisson, riz. Champon ou sara-udon au quartier chinois.",
    p: [["Croisière Gunkanjima (port de Nagasaki)", "軍艦島コンシェルジュ"], ["Pont Megane", "眼鏡橋 長崎"], ["Sofuku-ji", "崇福寺 長崎"], ["Quartier chinois", "長崎新地中華街"]] },
  kumamoto: { t: "Kumamoto", d: "Le château, la rue Sakuranobaba, le jardin Suizenji.", full: true, city: "Kumamoto", out: ["lunch"], pass: "Pass Kyushu · jour 4",
    go: "Après le kick : Shinkansen environ 35 min, puis tram.",
    eat: "Basashi (cheval cru) : très maigre, très protéiné. La spécialité à goûter.",
    p: [["Château de Kumamoto", "熊本城"], ["Sakuranobaba Josaien", "桜の馬場 城彩苑"], ["Jardin Suizenji", "水前寺成趣園"]] },
  takeo: { t: "Takeo-Onsen & Ureshino", d: "Bains, bibliothèque et camphrier géant à Takeo, puis onsen et tofu cuit à l'eau thermale à Ureshino.", full: true, city: "Takeo", out: ["lunch"], pass: "Pass Kyushu · jour 5",
    go: "Train jusqu'à Takeo-Onsen (environ 1h), puis Shinkansen une station jusqu'à Ureshino-Onsen.",
    eat: "Le yudofu d'Ureshino (tofu fondant à l'eau thermale) : parfait pour ta sèche.",
    p: [["Takeo-Onsen (porte Romon)", "武雄温泉 楼門"], ["Bibliothèque de Takeo", "武雄市図書館"], ["Camphrier de Takeo", "武雄の大楠"], ["Ureshino Onsen", "嬉野温泉 シーボルトの湯"]] },
  hakozaki: { t: "Hakozaki-gu & musée d'art asiatique", d: "Le grand sanctuaire de Hakozaki, puis le musée d'art asiatique.",
    go: "Métro.",
    p: [["Hakozaki-gu", "筥崎宮"], ["Musée d'art asiatique", "福岡アジア美術館"]] },
  avispaGamba: { t: "Avispa Fukuoka – Gamba Osaka", d: "Match de J1 à 19h au stade Best Denka.", evening: true, out: ["dinner"],
    go: "Bus depuis Hakata.", eat: "Mange avant d'y aller, ou yakitori au stade.",
    p: [["Stade Best Denka", "ベスト電器スタジアム"]] },
  maizuru: { t: "Parc Maizuru, Daimyo & Yakuin", d: "Les ruines du château, puis cafés et friperies de Daimyo et Yakuin.",
    p: [["Parc Maizuru (château de Fukuoka)", "舞鶴公園 福岡城跡"], ["Daimyo", "大名 福岡市中央区"], ["Yakuin", "薬院駅"]] },
  okunchi: { t: "Hakata Okunchi", d: "La fête d'automne de Kushida-jinja.", tip: "Dates à vérifier (23–24 oct.).",
    p: [["Kushida-jinja", "櫛田神社 福岡"]] },
  yameUkiha: { t: "Yame & Ukiha", d: "Yame le matin (quartier des artisans, Konomi Honke), puis Ukiha l'après-midi (quartier Shirakabe, sanctuaire aux 91 torii).", full: true, city: "Yame", out: ["lunch"],
    go: "Yame : JR jusqu'à Hainuzuka, puis bus. Ukiha : train jusqu'à Kurume, puis ligne JR Kyudai.",
    tip: "Les champs de thé sont difficiles d'accès sans voiture.",
    eat: "Soba au thé vert de Yame, ou teishoku.",
    p: [["Yame Fukushima (quartier des artisans)", "八女福島 白壁の町並み"], ["Konomi Honke", "Konomi Honke Yame"], ["Ukiha, quartier Shirakabe", "筑後吉井 白壁の町並み"], ["Ukiha Inari-jinja (91 torii)", "浮羽稲荷神社"]] },
  hiko: { t: "Mont Hiko", d: "Funiculaire, sanctuaire, puis descente à pied.", full: true, city: "Soeda", out: ["lunch"],
    go: "JR jusqu'à Soeda, bus BRT Hikoboshi, puis bus local jusqu'au funiculaire. Environ 2h30 par trajet : pars tôt et vérifie les horaires.",
    eat: "Peu de restos là-haut : prends un bento maison.",
    p: [["Funiculaire du mont Hiko", "英彦山スロープカー"], ["Hikosan-jingu", "英彦山神宮"]] },
  prepTokyo: { t: "Préparer Tokyo", d: "Valise, batch cooking léger, SUGOCA rechargée.", p: [] },

  /* ---------------- NOVEMBRE ---------------- */
  retourTokyo: { t: "Retour de Tokyo", d: "Journée tranquille.", p: [] },
  asaGeiko: { t: "Asa-geiko à Sumiyoshi-jinja", d: "Entraînement de sumo du matin (7h–9h), gratuit. Puis petit-déj au marché Yanagibashi (environ 15 min à pied).", morning: true, out: ["breakfast"],
    tip: "Reste silencieux et ne parle pas au maître d'écurie.",
    eat: "Au marché Yanagibashi : bol de sashimi ou poisson grillé, parfait le matin.",
    p: [["Sumiyoshi-jinja", "住吉神社 福岡"], ["Marché Yanagibashi", "柳橋連合市場"]] },
  yobukoKaratsu: { t: "Yobuko & Karatsu", d: "Le marché du matin et le calamar de Yobuko, puis le château de Karatsu et la pinède Niji no Matsubara.", full: true, city: "Karatsu", out: ["lunch"],
    go: "Train direct jusqu'à Karatsu (ligne de métro Kuko prolongée par la JR), puis bus Showa jusqu'à Yobuko.",
    tip: "Le marché ferme vers midi : pars tôt. Alternative : match d'Avispa contre Nagasaki à 15h.",
    eat: "Ika-ikizukuri (calamar vivant en sashimi) : presque que des protéines.",
    p: [["Marché du matin de Yobuko", "呼子朝市"], ["Château de Karatsu", "唐津城"], ["Niji no Matsubara", "虹の松原"]] },
  arita: { t: "Arita & Mifuneyama illuminé", d: "Le village de la porcelaine, puis le jardin de Mifuneyama illuminé le soir.", full: true, city: "Arita", out: ["lunch", "dinner"],
    go: "Train jusqu'à Takeo-Onsen. Arita est à environ 20 min en train. Mifuneyama : bus ou environ 30 min à pied depuis la gare de Takeo-Onsen.",
    eat: "Teishoku servi dans de la vaisselle d'Arita.",
    p: [["Arita, quartier Uchiyama", "有田 内山地区"], ["Mifuneyama Rakuen", "御船山楽園"]] },
  tower: { t: "Fukuoka Tower & musée de la ville", d: "La tour sur le front de mer, puis le musée de la ville.",
    go: "Bus depuis Tenjin.",
    p: [["Fukuoka Tower", "福岡タワー"], ["Musée de la ville de Fukuoka", "福岡市博物館"]] },
  ainoshima: { t: "Ainoshima, l'île aux chats", d: "Tour de l'île à pied.", full: true,
    go: "Train Nishitetsu jusqu'à Nishitetsu-Shingu, environ 15 min à pied jusqu'au port, puis ferry d'environ 20 min.",
    p: [["Port de Shingu", "新宮港 福岡"], ["Ainoshima", "相島 新宮町"]] },
  kashii: { t: "Kashii-gu", d: "Grand sanctuaire et son allée de camphriers.",
    go: "Train JR jusqu'à Kashii-Jingu.",
    p: [["Kashii-gu", "香椎宮"]] },
  shikanoshima: { t: "Shikanoshima", d: "Ferry, tour de l'île à pied, fruits de mer.", out: ["lunch"],
    go: "Ferry depuis Bayside Place, environ 30 min.",
    eat: "Fruits de mer grillés ou sazae (bigorneau) : top en protéines.",
    p: [["Bayside Place (ferry)", "ベイサイドプレイス博多"], ["Shikaumi-jinja", "志賀海神社"]] },
  asaGeiko2: { t: "Asa-geiko de l'écurie Takasago", d: "Entraînement de sumo gratuit au temple Jodo-ji, vers 8h.", morning: true,
    go: "Métro Tojinmachi, 3 min à pied.", tip: "Reste silencieux.",
    p: [["Temple Jodo-ji (Tojinmachi)", "浄土寺 福岡市中央区 唐人町"]] },
  shofuen: { t: "Shofuen & Rakusuien", d: "Deux petits jardins japonais : matcha et début des couleurs.",
    go: "Shofuen à pied depuis Yakuin, Rakusuien à pied depuis la gare de Hakata.",
    p: [["Shofuen", "松風園 福岡"], ["Rakusuien", "楽水園 福岡"]] },
  hita: { t: "Hita", d: "Le quartier historique de Mameda-machi et sa brasserie de saké.", full: true, city: "Hita", out: ["lunch"],
    go: "Bus express depuis Hakata, environ 1h20.",
    eat: "Le Hita yakisoba est gras : prends plutôt un teishoku de poisson ou d'ayu grillé.",
    p: [["Mameda-machi", "豆田町 日田"], ["Brasserie Kuncho", "薫長酒造 日田"]] },
  akizuki: { t: "Akizuki & Nyoirin-ji", d: "Les érables d'Akizuki, puis Nyoirin-ji, le temple aux grenouilles.", full: true, city: "Asakura", out: ["lunch"],
    go: "Train Nishitetsu ligne Amagi jusqu'à Amagi, puis bus d'environ 20 min. Nyoirin-ji au retour, à pied depuis une gare d'Ogori (vérifie l'itinéraire).",
    eat: "Soba ou teishoku dans le vieux village.",
    p: [["Akizuki (allée des samouraïs)", "秋月城跡 杉の馬場"], ["Nyoirin-ji", "如意輪寺 小郡"]] },
  yusentei: { t: "Jardin Yusentei", d: "Érables et matcha dans une ancienne villa de seigneur.",
    p: [["Yusentei", "友泉亭公園"]] },
  dazaifu2: { t: "Komyozen-ji & Kamado-jinja", d: "Le jardin de mousse et de pierre de Komyozen-ji, puis Kamado-jinja dans les érables.", full: true, city: "Dazaifu", out: ["lunch"],
    go: "Bus entre les deux.", tip: "Journée dense : choisis l'un des deux si besoin.",
    p: [["Komyozen-ji", "光明禅寺 太宰府"], ["Kamado-jinja", "竈門神社 太宰府"]] },
  ohoriJardin: { t: "Jardin japonais du parc Ohori", d: "Les érables du jardin.",
    p: [["Jardin japonais d'Ohori", "大濠公園日本庭園"]] },
  kawachi: { t: "Kawachi Fujien & Kokura", d: "Le tunnel d'érables de Kawachi Fujien (moins de monde en semaine), le château de Kokura et le marché Tanga.", full: true, city: "Kitakyushu", out: ["lunch"],
    go: "JR jusqu'à Yahata, bus Nishitetsu, environ 15 min à pied, puis train jusqu'à Kokura.",
    tip: "Billets Kawachi Fujien à acheter avant.",
    eat: "Marché Tanga : sashimi, poisson grillé, oden.",
    p: [["Kawachi Fujien", "河内藤園"], ["Château de Kokura", "小倉城"], ["Marché Tanga", "旦過市場"]] },
  hiroshima1: { t: "Hiroshima, jour 1", d: "Parc du Mémorial de la Paix, musée, Dôme de Genbaku, jardin Shukkeien. Le soir : okonomiyaki.", full: true, city: "Hiroshima", night: "Hiroshima", out: ["lunch", "dinner"],
    go: "Shinkansen, environ 1h05 (billet à part, non couvert par les pass JR Kyushu).",
    eat: "Okonomiyaki : version soba, sans mayonnaise, ~800 kcal. C'est ton repas plaisir.",
    p: [["Parc du Mémorial de la Paix", "広島平和記念公園"], ["Musée du Mémorial de la Paix", "広島平和記念資料館"], ["Dôme de Genbaku", "原爆ドーム"], ["Jardin Shukkeien", "縮景園"], ["Okonomimura", "お好み村 広島"]] },
  hiroshima2: { t: "Miyajima", d: "Sanctuaire d'Itsukushima, mont Misen, vallon Momijidani. Goûter les huîtres.", full: true, city: "Hiroshima", out: ["breakfast", "lunch", "dinner"],
    tip: "Taxe d'entrée sur l'île à prévoir (environ 100 yens).",
    eat: "Huîtres grillées : très protéinées, peu caloriques. Évite les momiji manju (sucrés).",
    p: [["Embarcadère de Miyajimaguchi", "宮島口桟橋"], ["Sanctuaire d'Itsukushima", "嚴島神社"], ["Téléphérique du mont Misen", "宮島ロープウエー"], ["Momijidani", "紅葉谷公園 宮島"]] },
  noelTenjin: { t: "Marché de Noël de Tenjin & Nakasu", d: "Repos, puis le soir : marché de Noël de Tenjin et illuminations de Nakasu.", evening: true,
    p: [["Marché de Noël de Tenjin", "クリスマスマーケット 福岡市役所 ふれあい広場"], ["Nakasu", "中洲 福岡"]] },
  minami: { t: "Parc Minami", d: "Zoo et jardin botanique.",
    go: "Bus depuis Tenjin.",
    p: [["Zoo et jardin botanique de Fukuoka", "福岡市動植物園"]] },
  avispaMarinos: { t: "Avispa – Yokohama F. Marinos & marché de Noël", d: "Match à 19h, puis marché de Noël de la gare de Hakata (ouvert jusqu'à 23h en 2025).", evening: true, out: ["dinner"],
    go: "Bus depuis Hakata.",
    p: [["Stade Best Denka", "ベスト電器スタジアム"], ["Marché de Noël de Hakata", "JR博多シティ クリスマスマーケット"]] },
  saga: { t: "Saga", d: "Le château et le musée du château de Saga.", city: "Saga", out: ["lunch"],
    go: "Train JR, environ 40 min.",
    eat: "Bœuf de Saga : prends un morceau maigre (filet, akami).",
    p: [["Musée du château de Saga", "佐賀城本丸歴史館"]] },
  iki: { t: "Île d'Iki", d: "Jetfoil depuis le port de Hakata, puis bus sur l'île.", full: true, city: "Iki", out: ["lunch"],
    go: "Jetfoil environ 1h10 depuis le port de Hakata.",
    tip: "Vérifie la météo et l'heure du dernier bateau.",
    eat: "Uni, poisson grillé, bœuf d'Iki : de quoi bien manger protéiné.",
    p: [["Terminal des ferries de Hakata", "博多ふ頭 第2ターミナル"], ["Saru-iwa (rocher du singe)", "猿岩 壱岐"], ["Tsukiyomi-jinja", "月讀神社 壱岐"]] },
  itoshimaMont: { t: "Itoshima côté montagne", d: "Sennyo-ji et la cascade Shiraito dans les érables.", full: true, city: "Itoshima", out: ["lunch"],
    go: "Train JR jusqu'à Chikuzen-Maebaru, puis bus communautaire d'Itoshima. Très peu de bus : vérifie les horaires avant.",
    tip: "Alternative : basket, Rizing Zephyr Fukuoka à Island City à 14h05.",
    eat: "Nagashi-somen ou truite grillée près de la cascade.",
    p: [["Sennyo-ji Daihio-in", "雷山千如寺大悲王院"], ["Cascade Shiraito", "白糸の滝 糸島"]] },
  mojiko: { t: "Mojiko Retro & Shimonoseki", d: "Mojiko Retro, tunnel piéton jusqu'à Shimonoseki, marché Karato (sushis le week-end), sanctuaire Akama.", full: true, city: "Kitakyushu", out: ["lunch"],
    go: "Train JR jusqu'à Mojiko, environ 1h30.",
    eat: "Sushis du marché Karato. Le yaki-curry de Mojiko est lourd : à éviter.",
    p: [["Mojiko Retro", "門司港レトロ"], ["Tunnel piéton du Kanmon", "関門トンネル人道 門司側"], ["Marché Karato", "唐戸市場"], ["Sanctuaire Akama", "赤間神宮"]] },

  /* ---------------- DÉCEMBRE ---------------- */
  nakasuYatai: { t: "Illuminations de Nakasu & yatai", d: "Le soir : illuminations et dîner dans un yatai.", evening: true, out: ["dinner"],
    eat: "Au yatai : yakitori au sel, oden, gyoza en petite quantité. Évite le ramen en fin de soirée.",
    p: [["Yatai de Nakasu", "中洲屋台"]] },
  canal: { t: "Canal City & Ramen Stadium", d: "Les illuminations de Canal City et le Ramen Stadium.", out: ["dinner"],
    go: "À pied depuis Hakata.", eat: "Un bol de ramen, sans riz ni gyoza, bouillon à moitié.",
    p: [["Canal City Hakata", "キャナルシティ博多"], ["Ramen Stadium", "キャナルシティ ラーメンスタジアム"]] },
  recup: { t: "Récupération", d: "Journée libre pour souffler.", full: true, p: [] },
  kawabata: { t: "Kawabata & artisanat de Hakata", d: "La galerie marchande Kawabata et le centre d'artisanat de Hakata.",
    go: "À pied depuis Nakasu-Kawabata.",
    p: [["Galerie Kawabata", "川端通商店街"], ["Hakata Dento Kogeikan", "博多伝統工芸館"]] },
  kakigoya: { t: "Itoshima, cabane à huîtres", d: "Déjeuner dans une kaki-goya. Le soir après le travail : motsunabe au restaurant.", full: true, city: "Itoshima", out: ["lunch", "dinner"],
    go: "Train JR jusqu'à Chikuzen-Maebaru puis bus, horaires à vérifier.",
    eat: "Huîtres grillées : très protéinées et légères. Le motsunabe, c'est des abats gras : petite portion, sans le champon à la fin.",
    p: [["Cabanes à huîtres de Kishi", "岐志漁港 牡蠣小屋"], ["Motsunabe (Hakata)", "もつ鍋 博多"]] },
  yanagawa: { t: "Yanagawa", d: "Promenade en barque avec kotatsu, puis anguille (unagi seiro-mushi).", full: true, city: "Yanagawa", out: ["lunch"],
    go: "Train Nishitetsu direct depuis Tenjin, environ 50 min.",
    eat: "Unagi seiro-mushi : riche (~900 kcal) et sauce sucrée. C'est ton repas plaisir de la semaine.",
    p: [["Promenade en barque", "柳川 川下り"], ["Ganso Motoyoshiya (unagi)", "元祖本吉屋 柳川"]] },
  marathon: { t: "Marathon international de Fukuoka", d: "Départ à 12h10 au stade Heiwadai, dans le parc Maizuru. Ensuite, balade au parc Ohori.",
    go: "Métro jusqu'à Ohorikoen ou Akasaka.",
    tip: "Gratuit. Coureurs d'élite, ambiance au bord de la route.",
    p: [["Stade Heiwadai", "平和台陸上競技場"], ["Parc Ohori", "大濠公園 福岡"]] },
  futsukaichi: { t: "Onsen de Futsukaichi", d: "Un bain chaud après le kick.",
    go: "Train JR depuis Hakata, environ 15 min.",
    p: [["Hakata-yu (Futsukaichi)", "博多湯 二日市温泉"]] },
  yoshinogari: { t: "Yoshinogari", d: "Le grand site préhistorique reconstitué.", full: true, city: "Yoshinogari", out: ["lunch"],
    go: "Train JR jusqu'à Yoshinogari-koen, environ 1h.",
    eat: "Restos du parc limités : bento maison ou konbini.",
    p: [["Parc historique de Yoshinogari", "吉野ヶ里歴史公園"]] },
  hanamidori: { t: "Mizutaki chez Hanamidori", d: "Le mizutaki de Hakata au restaurant (déjeuner tardif ou soir).", out: ["dinner"],
    eat: "Le mizutaki, c'est ton plat idéal : bouillon, poulet, légumes. Zosui à la fin si tu as faim.",
    p: [["Hanamidori (Hakata)", "華味鳥 博多駅前店"]] },
  daimyoNoel: { t: "Cafés de Daimyo & marché de Noël", d: "Cafés de Daimyo, puis marché de Noël de Tenjin.",
    p: [["Daimyo", "大名 福岡市中央区"], ["Marché de Noël de Tenjin", "クリスマスマーケット 福岡市役所 ふれあい広場"]] },
  huisTenBosch: { t: "Huis Ten Bosch", d: "Les illuminations d'hiver.", full: true, city: "Sasebo", out: ["lunch", "dinner"], pass: "Pass Nord · jour 1",
    go: "Train express direct depuis Hakata, environ 1h45. Retour tard.",
    tip: "À éviter si c'est ta semaine de kick du vendredi soir.",
    eat: "Les restos du parc sont chers et souvent frits : prévois salad chicken + onigiri.",
    p: [["Huis Ten Bosch", "ハウステンボス"]] },
  beppu: { t: "Beppu", d: "Les « enfers » de Beppu, bain dans un onsen, nuit sur place.", full: true, city: "Beppu", night: "Beppu", out: ["lunch", "dinner"], pass: "Pass Nord · jour 2",
    go: "Train, environ 2h.",
    eat: "Jigoku-mushi : légumes, œufs et poisson cuits à la vapeur des sources. Parfait. Le toriten est frit : à limiter.",
    p: [["Enfers de Beppu (Umi Jigoku)", "海地獄 別府"], ["Jigoku-mushi Kobo", "地獄蒸し工房 鉄輪"], ["Takegawara Onsen", "竹瓦温泉"]] },
  yufuin: { t: "Yufuin", d: "La rue Yunotsubo, le lac Kinrin, retour en train ou en bus.", full: true, city: "Yufuin", out: ["breakfast", "lunch"], pass: "Pass Nord · jour 3",
    eat: "Bœuf de Bungo en teppanyaki (morceau maigre), ou soba.",
    p: [["Rue Yunotsubo", "湯の坪街道"], ["Lac Kinrin", "金鱗湖"]] },
  kurokawa1: { t: "Kurokawa Onsen", d: "Bus direct, puis nuit dans un ryokan.", full: true, city: "Kurokawa", night: "Kurokawa", out: ["lunch", "dinner"],
    go: "Bus direct depuis Tenjin, environ 3h, 3 bus par jour, réservation obligatoire.",
    eat: "Dîner kaiseki du ryokan : profite, c'est un repas d'exception.",
    p: [["Kurokawa Onsen", "黒川温泉 旅館組合 風の舎"]] },
  kurokawa2: { t: "Kurokawa, les trois bains", d: "Trois bains avec le pass (nyuto tegata), retour en bus l'après-midi. Le soir : marché de Noël de Tenjin.", full: true, city: "Kurokawa", out: ["breakfast", "lunch"],
    eat: "Petit-déj du ryokan : poisson, tofu, œufs, riz. Parfait.",
    p: [["Kurokawa Onsen", "黒川温泉 旅館組合 風の舎"], ["Marché de Noël de Tenjin", "クリスマスマーケット 福岡市役所 ふれあい広場"]] },
  souvenirs: { t: "Souvenirs", d: "Mentaiko et artisanat de Hakata.",
    p: [["Ming (gare de Hakata)", "博多駅 マイング"], ["Hakata Dento Kogeikan", "博多伝統工芸館"]] },
  basketKurume: { t: "Basket : Rizing Zephyr – Fukushima", d: "Match à 19h05 à la Kurume Arena (environ 2 000 yens au 2e étage).", evening: true, city: "Kurume", out: ["dinner"],
    p: [["Kurume Arena", "久留米アリーナ"]] },
  avispaShimizu: { t: "Avispa – Shimizu & mont Sarakura", d: "Dernier match à domicile à 14h30. Le soir : vue depuis le mont Sarakura.", full: true, out: ["dinner"],
    go: "Stade Best Denka : bus depuis Hakata. Mont Sarakura : JR jusqu'à Yahata, navette puis téléphérique.",
    p: [["Stade Best Denka", "ベスト電器スタジアム"], ["Téléphérique du mont Sarakura", "皿倉山ケーブルカー"]] },
  adieux: { t: "Dernier jour", d: "Yatai d'adieu à Nakasu et marché de Noël de la gare de Hakata.", evening: true, out: ["dinner"],
    p: [["Yatai de Nakasu", "中洲屋台"], ["Marché de Noël de Hakata", "JR博多シティ クリスマスマーケット"]] },

  /* ---------------- PLAN B (non placées) ---------------- */
  yanagibashi: { t: "Marché Yanagibashi", d: "Le marché couvert du matin : poisson, sashimi, petit-déj.", b: "Près du centre", out: ["breakfast"],
    p: [["Marché Yanagibashi", "柳橋連合市場"]] },
  sumiyoshi: { t: "Sumiyoshi-jinja", d: "Un des plus anciens sanctuaires de Fukuoka, à 15 min à pied de Hakata.", b: "Près du centre",
    p: [["Sumiyoshi-jinja", "住吉神社 福岡"]] },
  museeAsie: { t: "Musée d'art asiatique", d: "Art contemporain d'Asie, à Hakata Riverain.", b: "Jour de pluie",
    p: [["Musée d'art asiatique", "福岡アジア美術館"]] },
  museeArt: { t: "Musée d'art de Fukuoka", d: "Dans le parc Ohori.", b: "Jour de pluie",
    p: [["Musée d'art de Fukuoka", "福岡市美術館"]] },
  museeVille: { t: "Musée de la ville de Fukuoka", d: "L'histoire de Fukuoka, avec le sceau d'or.", b: "Jour de pluie",
    p: [["Musée de la ville", "福岡市博物館"]] },
  museeKyushu: { t: "Musée national de Kyushu", d: "À Dazaifu.", b: "Jour de pluie", full: true,
    p: [["Musée national de Kyushu", "九州国立博物館"]] },
  canalPluie: { t: "Canal City", d: "Galerie couverte, boutiques, spectacle de fontaines.", b: "Jour de pluie",
    p: [["Canal City Hakata", "キャナルシティ博多"]] },
  yataiSoir: { t: "Yatai de Nakasu", d: "Un soir après le travail.", b: "Le soir", evening: true, out: ["dinner"],
    eat: "Yakitori au sel, oden. Pas de ramen de fin de soirée.",
    p: [["Yatai de Nakasu", "中洲屋台"]] },
  motsunabe: { t: "Motsunabe", d: "Le pot-au-feu d'abats de Hakata.", b: "Le soir", evening: true, out: ["dinner"],
    eat: "Petite portion, sans le champon à la fin.",
    p: [["Motsunabe (Hakata)", "もつ鍋 博多"]] },
  avispaNagasaki: { t: "Avispa – Nagasaki", d: "Match à 15h le sam. 7 nov.", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム"]] },
  avispaOkayama: { t: "Avispa – Okayama", d: "Match à 15h le sam. 10 oct.", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム"]] },
  avispaDec: { t: "Avispa – match du 13 déc.", d: "Match à 15h le dim. 13 déc.", b: "Sport",
    p: [["Stade Best Denka", "ベスト電器スタジアム"]] },
  basketIsland: { t: "Basket : Rizing Zephyr à Island City", d: "Match le sam. 28 nov. à 14h05.", b: "Sport",
    p: [["Island City (Teriha)", "照葉積水ハウスアリーナ"]] },
};

/* ---------- Les jours : sport du matin + sorties ----------
   m : kick | salle | journee (sans salle) | weekend | tokyo | repos */
window.DAYS = {
  "2026-10-03": { m: "weekend", s: [] },
  "2026-10-04": { m: "weekend", s: [] },
  "2026-10-05": { m: "kick", s: ["hakataGion"] },
  "2026-10-06": { m: "journee", s: ["kurume"] },
  "2026-10-07": { m: "salle", s: ["nokonoshima"] },
  "2026-10-08": { m: "kick", s: ["ohori"] },
  "2026-10-09": { m: "journee", s: ["uminonakamichi"] },
  "2026-10-10": { m: "weekend", s: ["itoshimaMer"] },
  "2026-10-11": { m: "weekend", s: ["munakata"] },
  "2026-10-12": { m: "kick", s: ["atago"], ferie: true },
  "2026-10-13": { m: "journee", s: ["dazaifu"] },
  "2026-10-14": { m: "journee", s: ["yutoku"] },
  "2026-10-15": { m: "kick", s: ["nanzoin"] },
  "2026-10-16": { m: "journee", s: ["kagoshima"] },
  "2026-10-17": { m: "weekend", s: ["nagasaki1"] },
  "2026-10-18": { m: "weekend", s: ["nagasaki2"] },
  "2026-10-19": { m: "kick", s: ["kumamoto"] },
  "2026-10-20": { m: "journee", s: ["takeo"] },
  "2026-10-21": { m: "salle", s: ["hakozaki", "avispaGamba"] },
  "2026-10-22": { m: "kick", s: ["maizuru"] },
  "2026-10-23": { m: "salle", s: ["okunchi"] },
  "2026-10-24": { m: "weekend", s: ["yameUkiha"] },
  "2026-10-25": { m: "weekend", s: ["hiko"] },
  "2026-10-26": { m: "kick", s: ["prepTokyo"] },
  "2026-11-05": { m: "kick", s: ["retourTokyo"] },
  "2026-11-06": { m: "matin", s: ["asaGeiko"] },
  "2026-11-07": { m: "weekend", s: ["yobukoKaratsu"] },
  "2026-11-08": { m: "weekend", s: ["arita"] },
  "2026-11-09": { m: "kick", s: ["tower"] },
  "2026-11-10": { m: "journee", s: ["ainoshima"] },
  "2026-11-11": { m: "salle", s: ["kashii"] },
  "2026-11-12": { m: "kick", s: ["shikanoshima"] },
  "2026-11-13": { m: "matin", s: ["asaGeiko2", "shofuen"] },
  "2026-11-14": { m: "weekend", s: ["hita"] },
  "2026-11-15": { m: "weekend", s: ["akizuki"] },
  "2026-11-16": { m: "kick", s: ["yusentei"] },
  "2026-11-17": { m: "journee", s: ["dazaifu2"] },
  "2026-11-18": { m: "salle", s: ["ohoriJardin"] },
  "2026-11-19": { m: "kick", s: [] },
  "2026-11-20": { m: "journee", s: ["kawachi"] },
  "2026-11-21": { m: "weekend", s: ["hiroshima1"] },
  "2026-11-22": { m: "weekend", s: ["hiroshima2"] },
  "2026-11-23": { m: "kick", s: ["noelTenjin"], ferie: true },
  "2026-11-24": { m: "salle", s: ["minami"] },
  "2026-11-25": { m: "salle", s: ["avispaMarinos"] },
  "2026-11-26": { m: "kick", s: ["saga"] },
  "2026-11-27": { m: "journee", s: ["iki"] },
  "2026-11-28": { m: "weekend", s: ["itoshimaMont"] },
  "2026-11-29": { m: "weekend", s: ["mojiko"] },
  "2026-11-30": { m: "kick", s: ["nakasuYatai"] },
  "2026-12-01": { m: "salle", s: ["canal"] },
  "2026-12-02": { m: "journee", s: ["recup"] },
  "2026-12-03": { m: "kick", s: ["kawabata"] },
  "2026-12-04": { m: "journee", s: ["kakigoya"] },
  "2026-12-05": { m: "weekend", s: ["yanagawa"] },
  "2026-12-06": { m: "weekend", s: ["marathon"] },
  "2026-12-07": { m: "kick", s: ["futsukaichi"] },
  "2026-12-08": { m: "journee", s: ["yoshinogari"] },
  "2026-12-09": { m: "salle", s: ["hanamidori"] },
  "2026-12-10": { m: "kick", s: ["daimyoNoel"] },
  "2026-12-11": { m: "journee", s: ["huisTenBosch"] },
  "2026-12-12": { m: "weekend", s: ["beppu"] },
  "2026-12-13": { m: "weekend", s: ["yufuin"] },
  "2026-12-14": { m: "kick", s: [] },
  "2026-12-15": { m: "journee", s: ["kurokawa1"] },
  "2026-12-16": { m: "journee", s: ["kurokawa2"] },
  "2026-12-17": { m: "kick", s: ["souvenirs"] },
  "2026-12-18": { m: "salle", s: ["basketKurume"] },
  "2026-12-19": { m: "weekend", s: ["avispaShimizu"] },
  "2026-12-20": { m: "weekend", s: ["adieux"] },
};

/* ---------- Dates clés 2026 ---------- */
window.EVENTS = [
  { when: "7–9 oct.", from: "2026-10-07", what: "Nagasaki Kunchi", where: "En semaine, non placé. Week-end Nagasaki le 17–18 oct." },
  { when: "10–20 oct.", from: "2026-10-10", what: "Miyajidake, « chemin de lumière »", where: "Dim. 11 oct.", date: "2026-10-11" },
  { when: "12 oct.", from: "2026-10-12", what: "Jour férié (foule partout)", where: "" },
  { when: "23–24 oct.", from: "2026-10-23", what: "Hakata Okunchi, Kushida-jinja (à vérifier)", where: "Ven. 23 oct.", date: "2026-10-23" },
  { when: "30 oct.–3 nov.", from: "2026-10-30", what: "Saga Balloon Fiesta", where: "Raté (Tokyo)", missed: true },
  { when: "31 oct.–3 nov.", from: "2026-10-31", what: "Illuminations des temples de Gion", where: "Raté (Tokyo)", missed: true },
  { when: "2–4 nov.", from: "2026-11-02", what: "Karatsu Kunchi", where: "Raté (Tokyo)", missed: true },
  { when: "Début nov.", from: "2026-11-06", what: "Asa-geiko gratuit à Sumiyoshi-jinja", where: "Ven. 6 nov.", date: "2026-11-06" },
  { when: "8–22 nov.", from: "2026-11-08", what: "Tournoi de sumo de Kyushu : complet", where: "Remplacé par l'asa-geiko gratuit (6 nov.)" },
  { when: "Nov.–25 déc.", from: "2026-11-01", what: "Marchés de Noël", where: "Mer. 25 nov., mer. 16 déc." },
  { when: "23 nov.", from: "2026-11-23", what: "Jour férié", where: "" },
  { when: "6 déc.", from: "2026-12-06", what: "Marathon international de Fukuoka (gratuit)", where: "Dim. 6 déc.", date: "2026-12-06" },
];

/* ---------- À réserver ---------- */
window.BOOKINGS = [
  { id: "passKyushu", what: "Pass Tout Kyushu 5 jours (16–20 oct.) + réserver les places", for: "2026-10-16", cost: "24 000 ¥" },
  { id: "nagasaki", what: "Hôtel à Nagasaki (nuit du 17 oct.) et croisière Gunkanjima", for: "2026-10-17", cost: "hôtel 7 000–12 000 ¥ · croisière 3 600–4 700 ¥ + 650 ¥" },
  { id: "kawachi", what: "Billets Kawachi Fujien pour le 20 nov.", for: "2026-11-20" },
  { id: "hiroshima", what: "Hôtel à Hiroshima ou Miyajima (nuit du 21 nov.), réserver tôt", for: "2026-11-21", cost: "Shinkansen 8 570 ¥ l'aller" },
  { id: "passNord", what: "Pass Nord de Kyushu 3 jours (11–13 déc.)", for: "2026-12-11", cost: "15 000 ¥" },
  { id: "beppu", what: "Hôtel à Beppu ou Yufuin (nuit du 12 déc.)", for: "2026-12-12" },
  { id: "kurokawa", what: "Bus Kurokawa (réservation obligatoire) + ryokan (nuit du 15 déc.)", for: "2026-12-15", cost: "bus 7 500 ¥ A/R avec pass 3 bains · ryokan 20 000–40 000 ¥" },
  { id: "basket", what: "Billets basket du 18 déc. sur le site de Rizing Zephyr Fukuoka", for: "2026-12-18", cost: "~2 000 ¥" },
  { id: "sumo", what: "Sumo pas cher : surveiller la revente officielle au prix d'origine (chaise à l'étage, en semaine). Éviter les sites de revente privés.", for: "2026-11-08" },
];

/* ---------- Infos pratiques ---------- */
window.TRIP_RULES = [
  "Les sorties passent avant la salle. Les jours « Journée, sans salle », tu pars vers 9h et tu rentres avant 17h.",
  "Kick : lundi et jeudi 12h–13h (fixe). La sortie commence après, vers 13h30. Le vendredi soir une semaine sur deux ne gêne rien.",
  "Salle : mardi, mercredi, vendredi 10h–11h30, seulement les jours sans grande sortie.",
  "Travail : 17h/18h–20h, pas obligatoire : une belle sortie passe avant.",
  "Week-end : pas de travail, journées complètes.",
  "Les jours libres servent à souffler.",
];

window.TRANSPORT = [
  "Uniquement train, bus et marche. À la campagne, les bus passent rarement : vérifie les horaires la veille (Google Maps ou Navitime) et note l'heure du dernier retour.",
  "SUGOCA (l'équivalent JR Kyushu de la Suica) : au distributeur de n'importe quelle gare JR, touche « IC card » puis « SUGOCA ». 2 000 ¥ dont 500 de caution. Marche partout : trains, métro, bus, supérettes, et à Tokyo. Recharge aux distributeurs ou en supérette.",
  "Garde un peu de monnaie : certains bus de campagne ne prennent que les espèces.",
  "Shinkansen et trains express : billet en plus, au guichet ou au distributeur.",
];

window.PASSES = [
  { name: "Tout Kyushu, 5 jours", price: "24 000 ¥", days: "16–20 oct.", covers: "Kagoshima, Nagasaki, Kumamoto, Takeo et Ureshino", without: "env. 50 000 ¥" },
  { name: "Nord de Kyushu, 3 jours", price: "15 000 ¥", days: "11–13 déc.", covers: "Huis Ten Bosch, Beppu, Yufuin", without: "env. 20 000 ¥" },
];
window.PASS_NOTES = [
  "Conditions : être entré au Japon comme touriste (tampon « Temporary Visitor »). Garde ton passeport sur toi, il peut être demandé à bord.",
  "Achat : en ligne sur le site de JR Kyushu puis retrait à la gare de Hakata avec le passeport, ou directement au guichet.",
  "Places réservées gratuites avec le pass : réserve-les dès l'achat.",
  "Non couvert : Hakata–Hiroshima (8 570 ¥ l'aller), métro, bus et trains Nishitetsu.",
];

window.COSTS = [
  { group: "Transports", rows: [
    ["Carte SUGOCA", "2 000 ¥ une fois", "1 500 de crédit + 500 de caution"],
    ["Métro de Fukuoka", "210–380 ¥", "par trajet"],
    ["Hakata – Hiroshima", "8 570 ¥", "l'aller, non couvert par les pass"],
    ["Hakata – Nagasaki", "~6 000 ¥", "3 400 ¥ en « early 7 »"],
    ["Hakata – Kumamoto", "~5 300 ¥", "l'aller"],
    ["Hakata – Kagoshima", "~11 400 ¥", "l'aller"],
    ["Fukuoka – Kurokawa (bus)", "7 500 ¥", "A/R avec le pass 3 bains"],
    ["Hakata – Iki (jetfoil)", "~6 900 ¥", "l'aller"],
  ] },
  { group: "Visites", rows: [
    ["Croisière Gunkanjima", "3 600–4 700 ¥", "+ 650 ¥ en espèces"],
    ["Miyajima", "~2 400 ¥", "taxe, sanctuaire, téléphérique"],
    ["Musées de la Paix", "~200 ¥", ""],
    ["Jardins de Fukuoka", "100–300 ¥", "matcha 500–700 ¥"],
    ["Musée national, château de Kumamoto", "700–800 ¥", ""],
    ["Huis Ten Bosch", "7 000 ¥ et +", "le plus cher"],
    ["Match d'Avispa", "2 000–4 000 ¥", ""],
    ["Asa-geiko, sanctuaires, illuminations", "Gratuit", ""],
  ] },
  { group: "Manger et dormir", rows: [
    ["Bol de ramen", "800–1 200 ¥", ""],
    ["Soirée au yatai", "2 000–3 000 ¥", "souvent en espèces"],
    ["Motsunabe ou mizutaki", "2 000–4 000 ¥", ""],
    ["Cabane à huîtres", "2 000–3 000 ¥", ""],
    ["Anguille à Yanagawa", "4 000–5 000 ¥", ""],
    ["Hôtel simple", "7 000–12 000 ¥", "la nuit, plus cher en novembre"],
    ["Ryokan à Kurokawa", "20 000–40 000 ¥", "avec dîner"],
  ] },
];
